### ISSUE TITLE
Issue with soffice.bin and findPid in MacOS

### ISSUE THREAD

**Issue by xtuer** [sbraconnier/jodconverter#10]
1. In the class OfficeUtils, **EXECUTABLE_MAC_41** is should be **MacOS/soffice** instead of MacOS/soffice.bin

2. In the class OfficeProcess at line 343: pid = processManager.findPid(processQuery) in MacOS: 
the pid is always returned PID_NOT_FOUND that caused the program exit, I think there is error in the method findPid that is different with Ubuntu.

I changed MacOS/soffice.bin to **MacOS/soffice** and comment out the check of **if(pid == PID_NOT_FOUND)**, then the program can convert doc to html.

**Comment by sbraconnier** [comment]
Thanks a lot. I didn't have the chance to test my work on MacOS, so your help is greatly appreciated. I already fixed the EXECUTABLE_MAC_41 constant.

As for 2., I have to find the proper command in order to fix the way jodconverter retrieve the PID of the created office process. This PID is required when jodconverter is used with a pool of processes.

Not that easy to work on MacOS without MacOS ;). I'll find a way to run MacOS in a virtual box.

**Comment by sbraconnier** [comment]
Well, since I'm unable to find a free and working solution in order to run MacOs on my Windows laptop, I'll need help for this one.

The command which doesn't seem to work here is the following one:
```
/bin/bash -c /bin/ps -e -o pid,command | /bin/grep soffice | /bin/grep -v grep
```
Is there someone who could test this command on MacOS and write back here the output. If the command doesn't work, maybe the unix one will (already tested as working on ubuntu):

```
/bin/bash -c /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep
```

You will have to start an office process first in order to have an output (Open Office or Libre Office).

Thanks.

**Comment by javydreamercsw** [comment]
That's the issue with Mac and supporting Mac. Always such a pain to maintain and develop for. I usually opt for leaving it out.

**Comment by orimajp** [comment]
Where I checked the location of grep is different in macOS.

```
$ /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep
-bash: /bin/grep: No such file or directory
-bash: /bin/grep: No such file or directory

$ which grep
/usr/bin/grep
```

**Comment by sbraconnier** [comment]
Thanks for you help!

Then could you start Libre Office or Open Office and write back to me the output of both the following commands:

```
/bin/ps -e -o pid,args | /usr/bin/grep soffice | /usr/bin/grep -v grep
```
and
```
/bin/ps -e -o pid,command | /usr/bin/grep soffice | /usr/bin/grep -v grep
```
If you don't have Open Office or Libre Office installed, no worries. Just tell me if the commands succeeded. Or maybe you could try searching for another running process than "soffice".

**Comment by michelole** [comment]
Hi @sbraconnier!

I did the following:
- Installed `LibreOffice 5.2.7 for Mac OS X x86_64`
- Opened Writer

Please see commands and outputs below:

```
$ /bin/ps -e -o pid,args | /usr/bin/grep soffice | /usr/bin/grep -v grep
52128 /Applications/LibreOffice.app/Contents/MacOS/soffice -psn_0_4109291
```

```
$ /bin/ps -e -o pid,command | /usr/bin/grep soffice | /usr/bin/grep -v grep
52128 /Applications/LibreOffice.app/Contents/MacOS/soffice -psn_0_4109291
```

I can also provide additional support for macOS if needed.

**Comment by sbraconnier** [comment]
Thanks a lot @michelole!

I modified the Mac OS command according to your response and the commit is done.

Now I just need a confirmation from someone that the modification is enough to get the whole thing to work on Mac OS.

Could you build the project with this modification, and then tell me if you are able to convert a document ? Building the project with unit tests on should do the trick since some tests will fail if the PID cannot be retrieve.

**Comment by michelole** [comment]
Hello back!

Here is the relevant output from `gradle test`:
```
org.jodconverter.filter.GraphicInserterFilterTest STANDARD_OUT
    2017-06-08 18:49:38,113 [Test worker] DEBUG org.jodconverter.office.ProcessPoolOfficeManager - ProcessManager implementation is 'UnixProcessManager'
    2017-06-08 18:49:38,119 [Test worker] INFO  org.jodconverter.office.ManagedOfficeProcess - Submitting task 'Start' and waiting...
    2017-06-08 18:49:38,121 [OfficeProcessThread-0] DEBUG org.jodconverter.process.AbstractProcessManager - Finding PID using
    Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
    Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
    Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
    2017-06-08 18:49:38,230 [OfficeProcessThread-0] DEBUG org.jodconverter.process.AbstractProcessManager - Command Error: 
    /bin/bash: /bin/grep: No such file or directory
    /bin/bash: /bin/grep: No such file or directory
```

It seems it is using a **UnixProcessManager** and therefore your changes for MacProcessManager are not being applied.

[`SystemUtils.IS_OS_UNIX`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/SystemUtils.html#IS_OS_UNIX) returns true also for macOS. Try to change the if order at [line 52 of OfficeUtils](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/office/OfficeUtils.java#L52)! 😃

**Comment by sbraconnier** [comment]
Good catch! I didn't look at SystemUtils.IS_OS_UNIX, which will always return true for Mac OS. My bad!

**Comment by michelole** [comment]
Oops, I think it must be the other way around:

```
if (SystemUtils.IS_OS_MAC) {
    return new MacProcessManager();
} else if (SystemUtils.IS_OS_UNIX) {
    return new UnixProcessManager();
}
```

**Comment by sbraconnier** [comment]
haha! I hate not being able to test my stuff before commiting!!!

Thanks again.

**Comment by michelole** [comment]
Now it seems to get the `MacProcessManager` right, but then somehow fallback to `AbstractProcessManager` later:

```
org.jodconverter.filter.GraphicInserterFilterTest STANDARD_OUT
    2017-06-12 11:58:21,700 [Test worker] DEBUG org.jodconverter.office.ProcessPoolOfficeManager - ProcessManager implementation is 'MacProcessManager'
    2017-06-12 11:58:21,710 [Test worker] INFO  org.jodconverter.office.ManagedOfficeProcess - Submitting task 'Start' and waiting...
    2017-06-12 11:58:21,714 [OfficeProcessThread-0] DEBUG org.jodconverter.process.AbstractProcessManager - Finding PID using
    Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,command | /bin/grep soffice | /bin/grep -v grep]
    Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
    Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
    2017-06-12 11:58:21,848 [OfficeProcessThread-0] DEBUG org.jodconverter.process.AbstractProcessManager - Command Error: 
    /bin/bash: /bin/grep: No such file or directory
    /bin/bash: /bin/grep: No such file or directory
```

**Comment by michelole** [comment]
Please ignore the deleted comment, it was a fault on my side.

It seems tests are now passing! 😄 

We should, however, skip `unixProcessManager` test (as `windowsProcessManager` is being skipped):

```
org.jodconverter.process.ProcessManagerTest > macProcessManager PASSED

org.jodconverter.process.ProcessManagerTest > unixProcessManager STANDARD_OUT
    2017-06-12 12:15:26,557 [Test worker] DEBUG org.jodconverter.process.AbstractProcessManager - Finding PID using
    Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep sleep | /bin/grep -v grep]
    Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
    Regex used to match running office process we are looking for: \Qsleep\E.*\Q5s\E
    2017-06-12 12:15:26,600 [Test worker] DEBUG org.jodconverter.process.AbstractProcessManager - Command Error: 
    /bin/bash: /bin/grep: No such file or directory
    /bin/bash: /bin/grep: No such file or directory

org.jodconverter.process.ProcessManagerTest > unixProcessManager FAILED
    java.lang.AssertionError at ProcessManagerTest.java:55

org.jodconverter.process.ProcessManagerTest > windowsProcessManager SKIPPED
```

**Comment by sbraconnier** [comment]
Slowly we are getting there :)

**Comment by michelole** [comment]
Great news: `BUILD SUCCESSFUL` 👌 

You might be interested in this `WARN` debug message:

```
org.jodconverter.process.ProcessManagerTest > customProcessManagerFallback STANDARD_OUT
    2017-06-12 15:24:45,072 [Test worker] WARN  org.jodconverter.office.DefaultOfficeManagerBuilder - Ignoring custom process manager 'org.foo.fallback.ProcessManager': org.foo.fallback.ProcessManager
    java.lang.ClassNotFoundException: org.foo.fallback.ProcessManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.jodconverter.office.DefaultOfficeManagerBuilder.setProcessManager(DefaultOfficeManagerBuilder.java:270)
        at org.jodconverter.process.ProcessManagerTest.customProcessManagerFallback(ProcessManagerTest.java:151)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbraconnier** [comment]
Yeah, that's the expected behavior. It is part of the test customProcessManagerFallback, which tests that when a custom process manager cannot be found in the classpath, jodconverter will fall back to an auto-detect process manager.

Thanks a lot for your time and help. It's greatly appreciated!!
