### ISSUE TITLE
Fix regression introduced by #99. Use AOO libraries. 

### ISSUE THREAD

**Issue by sbraconnier** [sbraconnier/jodconverter#113]
Since #99, some filters do not work anymore. It seems that recent LO libraries not dot work well with Apache Open Office. But the AOO works well with recent LibreOffice. So we will use AOO libraries.

**Comment by surli** [comment]
Quick feedback: as part of upgrading an old instance of XWiki with a new version of jodconverter, we encountered also an issue while using the followings:
  * jodconverter 4.2.2
  * LO libraries 5.2.0 (unoil/juh/jurt/ridl)
  * LibreOffice 6.2.7.1

Here's an excerpt of the stack I got:
```
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 103
Exception Details:
  Location:
    org/jodconverter/task/AbstractLocalOfficeTask.loadDocument(Lorg/jodconverter/office/LocalOfficeContext;Ljava/io/File;)Lcom/sun/star/lang/XComponent; @103: astore_3
  Reason:
    Type 'com/sun/star/lang/IllegalArgumentException' (current frame, stack[0]) is not assignable to 'com/sun/star/uno/Exception' (stack map, stack[0])
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/lang/IllegalArgumentException' }
  Stackmap Frame:
    bci: @103
    flags: { }
    locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/uno/Exception' }
  Bytecode:
    0x0000000: 2bb9 0010 0100 2cb8 0011 1212 032a b600
    0x0000010: 13b8 0014 b900 1505 004e 2dbb 0016 59b7
    0x0000020: 0017 1219 b600 1a2c b600 1bb6 001a b600
    0x0000030: 1c03 bd00 1db8 001e 572d b04e bb00 2059
    0x0000040: bb00 1659 b700 1712 19b6 001a 2cb6 001b
    0x0000050: b600 1a12 21b6 001a 2db4 0022 b600 23b6
    0x0000060: 001c 2db7 0024 bf4e bb00 2059 bb00 1659
    0x0000070: b700 1712 19b6 001a 2cb6 001b b600 1ab6
    0x0000080: 001c 2db7 0024 bf                      
  Exception Handler Table:
    bci [0, 58] => handler: 59
    bci [0, 58] => handler: 103
    bci [0, 58] => handler: 103
  Stackmap Table:
    same_locals_1_stack_item_frame(@59,Object[#88])
    same_locals_1_stack_item_frame(@103,Object[#89])

	at org.jodconverter.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:187)
	at org.jodconverter.job.AbstractConversionJob.execute(AbstractConversionJob.java:57)
```

Apparently downgrading to the AOO libraries 4.1.2 solve the issue. So it looks like even using LO libraries with recent version of LO is not so stable, compared to using AOO libraries...

**Comment by dimitar90** [comment]
Hello fellos,
 I got the same problem even with downgraded AOO.. Have you been solved the issue further ?
