### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by EugenMayer** [sbraconnier/jodconverter#127]
I am currently trying to get the officeconverter build on java11.
For now building is fine, i also used the official openjdk11 docker image and also using libreoffice-6.1.5 ( j11 compat )

now during bootRun i get

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'conversionRestController': Unsatisfied dependency expressed through field 'converterService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'converterService' defined in file [/src/build/classes/java/main/de/kontextwork/converter/service/ConverterService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Invocation of init method failed; nested exception is org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' started but its pid could not be found
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at de.kontextwork.converter.ConverterApplication.main(ConverterApplication.java:21) ~[main/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.1.2.RELEASE.jar:2.1.2.RELEASE]
Ca
```

While i can start it on the cli without issues

```
soffice --headless
```

I upgraded all the spring / spring boot deps and jusing jodconverter 4.2.2:

https://github.com/EugenMayer/officeconverter/blob/master/build.gradle#L9

```
# java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode, sharing)


# soffice --version
LibreOffice 6.1.5.1 10(Build:1)
```

Are any issues known right now, maybe mit LibreOffice6 or something else? Thanks!

**Comment by EugenMayer** [comment]
You can try yourself by doing this

```
git clone https://github.com/EugenMayer/officeconverter
cd officeconverter
docker run -v ${PWD}/.:/src --rm eugenmayer/kontextwork-converter:development-11
```

if you want to investigate you can do
```
docker run -v ${PWD}/.:/src --rm -it --entrypoint /bin/bash  eugenmayer/kontextwork-converter:development-11
cd /src
./gradlew bootRun
```

Let me know if i can provide anything else

**Comment by EugenMayer** [comment]
any chance you could give me a hint @sbraconnier - could run this all with a debugger, but i am not sure what i am looking for since is actually it's an early bootstrap item

**Comment by sbraconnier** [comment]
Sorry for the delay!! I've been working a lot lately on projects at work! I'll try to take a look at this after work today. I'm not that familiar with Docker so i'll have to dive into it in order to fully understand what's going on!

But according to your previous posts, it seems that the started office PID cannot be retrieved. This is done using the [getRunningProcessesCommand](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/process/UnixProcessManager.java#L73) of the [UnixProcessManager](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/process/UnixProcessManager.java) since you are on linux.

The process manager is auto-detected. But it can be overriden by the [processManagerClass](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-spring-boot-starter/src/main/java/org/jodconverter/boot/autoconfigure/JodConverterLocalProperties.java#L97) when using the `jodconverter-spring-boot-starter` module.

**Comment by sbraconnier** [comment]
It would also help if you could set the log level to TRACE and put back here the results.

**Comment by sbraconnier** [comment]
I had time to work on this a little. When the TRACE log level is on, we can see what's happening:

2019-02-14 15:16:48.470 TRACE 315 --- [ProcessThread-0] o.j.process.AbstractProcessManager       : Command Error: /bin/sh: 1: /bin/ps: not found

Is it possible for you to ensure that those commands are there in your Docker image ?

**Comment by sbraconnier** [comment]
It seems to be the `/bin/ps` command that is not found. Maybe this could help:

[ps-command-doesnt-work-in-docker-container](https://stackoverflow.com/questions/26982274/ps-command-doesnt-work-in-docker-container)

**Comment by EugenMayer** [comment]
Wow, that's a nice finding.

According to 
https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L4 you are right

and since i switched from `debian:stretch` to `openjdk:11.0-jre-slim-stretch` when going to Java11, it makes sense that this is just not installed this time ( slim ). I will check that ASAP - thank you!

**Comment by EugenMayer** [comment]
Thank you, you nailed it. That fixed it. 

I went forward and made jodconverter compile under J11 with as few changes as possible - this was actually only upgrading gradle on 5.x and remove the wrapper install task.

Tests are good

**Comment by sbraconnier** [comment]
Closing, see #128
