### ISSUE TITLE
Could not establish connection

### ISSUE THREAD

**Issue by wingyiu** [sbraconnier/jodconverter#148]
```
Caused by: org.jodconverter.office.OfficeException: Could not establish connection
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:110)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:261)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:256)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jodconverter.office.RetryTimeoutException: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; null
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:64)
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
	... 7 common frames omitted
Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; null
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:170)
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
	... 9 common frames omitted
Caused by: com.sun.star.lang.IllegalArgumentException: null
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:118) [1 skipped]
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
	... 11 common frames omitted

Process finished with exit code 1
```

mac 10.11
libreoffice 4.3.7.2
jodconverter 4.2.2

```
jodconverter.local.enabled: true
jodconverter.local.officeHome: /Applications/LibreOffice.app/Contents
jodconverter.local.processTimeout: 10000
jodconverter.local.processRetryInterval: 250
```

**Comment by wingyiu** [comment]
solved by add dependency
```
'org.libreoffice:ridl:5.4.2',
            'org.libreoffice:juh:5.4.2',
            'org.libreoffice:jurt:5.4.2',
            'org.libreoffice:unoil:5.4.2',
```

**Comment by sbraconnier** [comment]
Thanks for letting me know. I think I will have to create 2 libraries `jodconverter-local-lo` and `jodconverter-local-oo` to ensure that OOo users could use the proper dependencies.

**Comment by wingyiu** [comment]
@sbraconnier add these libs cause #149 when deploy to Linux/Centos。I have removed these libs, and it work fine in both Mac and Linux , wired.
