### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by wingyiu** [sbraconnier/jodconverter#149]
```
[2019-05-23 13:23:57.165] ERROR [http-nio-20000-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet] [, ] - Servlet.service() for servlet [dispatcherServlet] in context with path [/doc-convert] threw exception [Handler dispatch failed; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 103
Exception Details:
  Location:
    org/jodconverter/task/AbstractLocalOfficeTask.loadDocument(Lorg/jodconverter/office/LocalOfficeContext;Ljava/io/File;)Lcom/sun/star/lang/XComponent; @103: astore_3
  Reason:
    Type 'com/sun/star/lang/IllegalArgumentException' (current frame, stack[0]) is not assignable to 'com/sun/star/uno/Exception' (stack map, stack[0])
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/lang/IllegalArgumentException' }
  Stackmap Frame:
    bci: @103
    flags: { }
    locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/uno/Exception' }
  Bytecode:
    0000000: 2bb9 0010 0100 2cb8 0011 1212 032a b600
    0000010: 13b8 0014 b900 1505 004e 2dbb 0016 59b7
    0000020: 0017 1219 b600 1a2c b600 1bb6 001a b600
    0000030: 1c03 bd00 1db8 001e 572d b04e bb00 2059
    0000040: bb00 1659 b700 1712 19b6 001a 2cb6 001b
    0000050: b600 1a12 21b6 001a 2db4 0022 b600 23b6
    0000060: 001c 2db7 0024 bf4e bb00 2059 bb00 1659
    0000070: b700 1712 19b6 001a 2cb6 001b b600 1ab6
    0000080: 001c 2db7 0024 bf
  Exception Handler Table:
    bci [0, 58] => handler: 59
    bci [0, 58] => handler: 103
    bci [0, 58] => handler: 103
  Stackmap Table:
    same_locals_1_stack_item_frame(@59,Object[#88])
    same_locals_1_stack_item_frame(@103,Object[#89])
] with root cause
java.lang.VerifyError: Stack map does not match the one at exception handler 103
Exception Details:
  Location:
    org/jodconverter/task/AbstractLocalOfficeTask.loadDocument(Lorg/jodconverter/office/LocalOfficeContext;Ljava/io/File;)Lcom/sun/star/lang/XComponent; @103: astore_3
  Reason:
    Type 'com/sun/star/lang/IllegalArgumentException' (current frame, stack[0]) is not assignable to 'com/sun/star/uno/Exception' (stack map, stack[0])
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/lang/IllegalArgumentException' }
  Stackmap Frame:
    bci: @103
    flags: { }
    locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/uno/Exception' }
  Bytecode:
    0000000: 2bb9 0010 0100 2cb8 0011 1212 032a b600
    0000010: 13b8 0014 b900 1505 004e 2dbb 0016 59b7
    0000020: 0017 1219 b600 1a2c b600 1bb6 001a b600
    0000030: 1c03 bd00 1db8 001e 572d b04e bb00 2059
    0000040: bb00 1659 b700 1712 19b6 001a 2cb6 001b
    0000050: b600 1a12 21b6 001a 2db4 0022 b600 23b6
    0000060: 001c 2db7 0024 bf4e bb00 2059 bb00 1659
    0000070: b700 1712 19b6 001a 2cb6 001b b600 1ab6
    0000080: 001c 2db7 0024 bf
  Exception Handler Table:
    bci [0, 58] => handler: 59
    bci [0, 58] => handler: 103
    bci [0, 58] => handler: 103
  Stackmap Table:
    same_locals_1_stack_item_frame(@59,Object[#88])
    same_locals_1_stack_item_frame(@103,Object[#89])

        at org.jodconverter.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:187)
        at org.jodconverter.job.AbstractConversionJob.execute(AbstractConversionJob.java:57)
```

centos 6.9
jod 4.2.2
jdk 1.8.0_b132
libreoffice 4.3.7.2 || libreoffice 6.0.4.2

**Comment by sbraconnier** [comment]
Could you please try with LibreOffice just to see what happens ?
