### ISSUE TITLE
Not able to start multiple OfficeProcesses

### ISSUE THREAD

**Issue by enigma969** [sbraconnier/jodconverter#15]
We run different instances of the same web application on our server, all of these instances want to start an Office process. Due to `OfficeProcess.checkForExistingProcess()`, only one Office process can be started, others fail to do so. 

```
org.jodconverter.office.OfficeException: Could not establish connection
	at org.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:104) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.ManagedOfficeProcess.access$100(ManagedOfficeProcess.java:40) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.ManagedOfficeProcess$4.call(ManagedOfficeProcess.java:279) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.ManagedOfficeProcess$4.call(ManagedOfficeProcess.java:275) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_72]
Caused by: org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' is already running; pid 30201
	at org.jodconverter.office.OfficeProcess.checkForExistingProcess(OfficeProcess.java:116) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.OfficeProcess.start(OfficeProcess.java:326) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.OfficeProcess.start(OfficeProcess.java:305) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:99) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]
	at org.jodconverter.office.ManagedOfficeProcess.access$100(ManagedOfficeProcess.java:40) ~[org.jodconverter.jodconverter-core-4.0.0-RELEASE.jar:4.0.0-RELEASE]

```

Any idea or workaround for this issue?

**Comment by sbraconnier** [comment]
This is the expected behavior. You cannot have multiple OfficeConnection for the same running office process. 

Instead, use a different port for each of your web application instances. This way, each of your web application instance will start an office process for its own needs.

You just have to configure the DefaultOfficeManagerBuilder so the port number (setPortNumber) is unique for each of your web app instance. The default port is 2002. I suggest you use 2002, 2003, 2004 ... and so on.

Sorry for the short anwser, I'm on my phone right now. Cheers!

**Comment by enigma969** [comment]
That helped, thank you!
