### ISSUE TITLE
There was an Exception after a while, and it persisted

### ISSUE THREAD

**Issue by luoluo001** [sbraconnier/jodconverter#154]
basis:
  I installed LibreOffice 6.2,and use project jodconverter-spring-boot-starter .
Jvm args -Doffice.home=/opt/libreoffice6.2
Configuration items：(application.yml)
 jodconverter:
  local:
    enabled: false
    port-numbers: 2005
    kill-existing-process: true
    process-timeout: 180000
    process-retry-interval: 1000
    max-tasks-per-process: 20
    task-execution-timeout: 60000
    task-queue-timeout: 60000
    document-format-registry: classpath:document-formats-finew.json
    format-options.txt.load.FilterOptions: utf16
    format-options.txt.store.TEXT.FilterOptions: utf16

and After running for some time, the following exception prevented the conversion.
Exception:
com.sun.star.lang.DisposedException: null
        at com.sun.star.lib.uno.environments.remote.JobQueue.removeJob(JobQueue.java:210)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:330)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
        at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
        at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
        at com.sun.proxy.$Proxy164.loadComponentFromURL(Unknown Source)
        at org.jodconverter.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:105)
        at org.jodconverter.task.LocalConversionTask.execute(LocalConversionTask.java:105)
        at org.jodconverter.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:148)
        at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:77)
        at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:73)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: com.sun.star.io.IOException: EOF reached - socket,host=127.0.0.1,port=2005,tcpNoDelay=1,localHost=localhost,localPort=34912,peerHost
=localhost,peerPort=2005
        at com.sun.star.lib.uno.bridges.java_remote.XConnectionInputStream_Adapter.read(XConnectionInputStream_Adapter.java:55)
        at java.io.DataInputStream.readInt(DataInputStream.java:387)
        at com.sun.star.lib.uno.protocols.urp.urp.readBlock(urp.java:355)
        at com.sun.star.lib.uno.protocols.urp.urp.readMessage(urp.java:92)
        at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge$MessageDispatcher.run(java_remote_bridge.java:105).

Thank you for looking at it!

**Comment by luoluo001** [comment]
supplement：
 LibreOffice installation process
download
  LibreOffice_6.2.4_Linux_x86-64_rpm_langpack_zh-CN.tar.gz
   LibreOffice_6.2.4_Linux_x86-64_rpm.tar.gz
  and unzip to each RPMS catalogue yum lcoalinstall *.rpm

**Comment by sbraconnier** [comment]
I'm currently on vacation. I won't be able to check this until next week. Sorry.

**Comment by luoluo001** [comment]
> I'm currently on vacation. I won't be able to check this until next week. Sorry.
Have a nice holiday! 
I did not install it through RPM, but directly through yum install libreoffice, and this problem did not appear later.  version 5.3.6.1 30(Build:1) of LibreOffice. 
Thank you for your answer！
