### ISSUE TITLE
It‘s not working on jre7？

### ISSUE THREAD

**Issue by mdzz0** [sbraconnier/jodconverter#156]
hi,   @sbraconnier  
First of all, Please forgiveness for my grammar mistakes.

Thanks for this library，but it‘s not working on jre7 ?

in my case, i got error “UnsupportedClassVersionError”;  but in the wiki ,i see “A Java runtime environment version 1.7 or higher.”,seem like it's should be support 1.7. 
https://github.com/sbraconnier/jodconverter/wiki/System-Requirements

Exception in thread "pool-4-thread-3" java.lang.UnsupportedClassVersionError: org/jodconverter/office/OfficeManager : Unsupported major.minor version 52.0 (unable to load class org.jodconverter.office.OfficeManager)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2922)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1174)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1669)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)

**Comment by mdzz0** [comment]
I using jodconverter-local-4.2.2

**Comment by mdzz0** [comment]
https://github.com/sbraconnier/jodconverter/wiki/Migration-Guide-4.1.1

I found this guide,  It's no support jre7 since version [4.1.1] , maybe you can update that wiki description;
 thanks for the wiki guide!
