### ISSUE TITLE
sample-webapp throws java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by axelrose** [sbraconnier/jodconverter#165]
Just some robustness on the sample webapp would be nice

If I open a fresh http://localhost:8080/jodconverter-sample-webapp/ and push "Convert!" without select some input file I get:

```
java.lang.IllegalArgumentException: Prefix string "" too short: length must be at least 3
        at java.base/java.io.File.createTempFile(File.java:2065)
        at java.base/java.io.File.createTempFile(File.java:2136)
        at org.jodconverter.sample.webapp.ConverterServlet.doPost(ConverterServlet.java:81)
```

Perhaps the code should just check for `uploadedFile == ""` too.

Thanks for making this such a nice project!
Axel.

**Comment by sbraconnier** [comment]
Fixed.
