### ISSUE TITLE
Task did not complete within timeout 

### ISSUE THREAD

**Issue by BaeSeulki** [sbraconnier/jodconverter#177]
Hi, I meet a timeout error in Linux while there is successful in macos. 
here is the out:
``` shell
Exception in thread "main" org.jodconverter.office.OfficeException: Task did not complete within timeout
        at org.jodconverter.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:93)
        at org.jodconverter.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:84)
        at org.jodconverter.office.LocalOfficeManager.execute(LocalOfficeManager.java:38)
        at org.jodconverter.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:189)
        at org.jodconverter.job.AbstractConversionJob.execute(AbstractConversionJob.java:57)
        at jodconverter.converter(jodconverter.java:35)
        at jodconverter.main(jodconverter.java:21)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.jodconverter.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:86)
        ... 6 more
```
how can I solve this.
this is my easy code:
``` java
public class jodconverter {
    public static void main(String[] args) throws Exception {
        // This example will force JODConverter to use the OpenOffice 4
        // installation that can be found using the specified path.
        OfficeManager officeManager =
                LocalOfficeManager.builder().portNumbers(8100)
                        .officeHome("/opt/libreoffice6.3")
                        .install().build();
        String relativelyPath=System.getProperty("user.dir");
        String docFileName = relativelyPath + "/abc.doc";
        String pdfFileName = relativelyPath + "/abc.pdf";
        converter(officeManager,docFileName,pdfFileName);
    }

    private static void converter(OfficeManager officeManager, String f1, String f2) throws Exception {
        File inputFile = new File(f1);
        File outputFile = new File(f2);
        try {
            // Start an office process and connect to the started instance (on port 2002).
            officeManager.start();

            // Convert
            JodConverter
                    .convert(inputFile)
                    .to(outputFile)
                    .execute();
            officeManager.stop();
        } finally {
            // Stop the office process
            OfficeUtils.stopQuietly(officeManager);
        }
    }
}
```

**Comment by BaeSeulki** [comment]
https://segmentfault.com/a/1190000015129654
