### ISSUE TITLE
SocketException: Connection reset Issue

### ISSUE THREAD

**Issue by NABEEL-AHMED-JAMIL** [sbraconnier/jodconverter#184]
@sbraconnier hi,
hope you are good and doing great. i'm facing issue socket exception any idea how to fix? 

here is my configuration

```
jodconverter:
    local:
        enabled: true
        port-numbers: 2002
        kill-existing-process: true
        process-timeout: 180000
        process-retry-interval: 1000
        max-tasks-per-process: 20
        task-execution-timeout: 140000
        task-queue-timeout: 90000
        format-options:
            html:
                store:
                    TEXT:
                        FilterOptions: EmbedImages
```

```
2020-01-16 17:54:06 [OfficeManagerPoolEntry-1] ERROR o.j.task.LocalConversionTask - Local conversion failed.
com.sun.star.lang.DisposedException: null
	at com.sun.star.lib.uno.environments.remote.JobQueue.removeJob(JobQueue.java:210)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:330)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy174.storeToURL(Unknown Source)
	at org.jodconverter.task.LocalConversionTask.storeDocument(LocalConversionTask.java:166)
	at org.jodconverter.task.LocalConversionTask.execute(LocalConversionTask.java:107)
	at org.jodconverter.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:148)
	at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:77)
	at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:73)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: com.sun.star.io.IOException: java.net.SocketException: Connection reset
	at com.sun.star.lib.uno.bridges.java_remote.XConnectionInputStream_Adapter.read(XConnectionInputStream_Adapter.java:55)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at com.sun.star.lib.uno.protocols.urp.urp.readBlock(urp.java:355)
	at com.sun.star.lib.uno.protocols.urp.urp.readMessage(urp.java:92)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge$MessageDispatcher.run(java_remote_bridge.java:105)

```

**Comment by sbraconnier** [comment]
Hello there!! I experienced that once and it was caused by a conversion of a specific document format (I think it was docx with an old LibreOffice version) that was not supported by the OpenOffice/LibreOffice version I was using. Could you try with another document format ??

What is the conversion (.xxx -> .yyy) you are trying to do ?

**Comment by NABEEL-AHMED-JAMIL** [comment]
@sbraconnier thanks for replay, i'm try to convert the txt file pdf, In txt file have hwp file content which i try to convert into pdf. it's work good but issue what i notes when file size grater then 5mb it's break connection. some time

**Comment by sbraconnier** [comment]
Ok I see... 

Is it possible for you to attach a file here I could work with to reproduce the anomaly. Try to remove any sensitive information from the file first.

Thanks!

**Comment by NABEEL-AHMED-JAMIL** [comment]
@sbraconnier i have hwp file which i'm sharing you
https://s3.us-east-1.amazonaws.com/www.webacq-sample.com/hwp_file_demo.html
i'm also sharing my code for running code it's will convert all type plz check
https://github.com/NABEEL-AHMED-JAMIL/RAAD-Converter
mvn spring-boot:run
http://localhost:8085/api/converter/swagger-ui.htm
File Number 7 which i'm trying to convert pdf

**Comment by NABEEL-AHMED-JAMIL** [comment]
@sbraconnier is possible to increase the timeout limit for socket?

**Comment by sbraconnier** [comment]
I'm not sure but I'll take a look. I won't have time this week but next week I should be able to work on this. I'll come back to you as soon as possible.

**Comment by NABEEL-AHMED-JAMIL** [comment]
@sbraconnier/jodconverter <jodconverter@noreply.github.com> no issue, and
thanks for replay

**Comment by sbraconnier** [comment]
I will have some time this week to check this issue. You said the the conversion process is TXT TO PDF, but the sample files are all hwp files. Am I suppose to convert them to TXT first using another tool ???

**Comment by NABEEL-AHMED-JAMIL** [comment]
i first extract the whole hwp file and make the stream of text then send to
the process of pdf.
After lot of testing, one think i notice the connection break when file are
big. so i did changes into setting by change the timeout and other few
setting, below link
https://github.com/NABEEL-AHMED-JAMIL/RAAD-Converter/blob/master/src/main/resources/application-loc.yml
,
and it's looks good, hope it's good further for future too.

Replay

**Comment by sbraconnier** [comment]
Glad to hear that changing some properties did the trick. The documentation of these options is [here](https://github.com/sbraconnier/jodconverter/wiki/Configuration).

**Comment by Adwaises** [comment]
Hello!

I want convert XLSX to PDF, but i get SocketException

**Comment by NABEEL-AHMED-JAMIL** [comment]
@Adwaises share xlsx file and also your configuration file for jod-converter

**Comment by Adwaises** [comment]
what  configuration file for jod-converter?
https://dropmefiles.com/eyM8e - xlsx file

**Comment by p4535992** [comment]
NABEEL i face the same issue about convert a xlsx to PDF can you ripristine the link for check your solution?  Ty.

**Comment by p4535992** [comment]
@NABEEL-AHMED-JAMIL , i have the same issue. Can you share the solution you found for your RAAD-Converter project ? The link are not usable anymore.

**Comment by NABEEL-AHMED-JAMIL** [comment]
#https://segmentfault.com/a/1190000015129654
#https://docs.alfresco.com/6.0/tasks/OOo-subsystems-config.html
#https://docs.alfresco.com/6.0/concepts/OOoJodconverter-subsystem-props.html
#//
https://github.com/LibreOffice/core/blob/master/filter/source/pdf/pdfexport.cxx#L459
#jodconverter.connectTimeout=20000
jodconverter:
local:
enabled: true
port-numbers: 2004
kill-existing-process: true
process-timeout: 180000
process-retry-interval: 1000
max-tasks-per-process: 20
task-execution-timeout: 140000
task-queue-timeout: 90000
working-dir: /tmp
format-options:
html:
store:
TEXT:
FilterOptions: EmbedImages my project setting for jodconvert and few
important link may help someone

**Comment by p4535992** [comment]
@Adwaises have you found a solution with the "RemoteOfficeManager" and "RemoteConverter" ?

**Comment by vinaysharma1987** [comment]
While we are converting from .docx to pdf we are getting following exception 
only when file size is more then 9MB 

org.jodconverter.core.office.OfficeException: Task did not complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties=null, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:104)
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:217)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:149)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:62)
