### ISSUE TITLE
Jodconverter randomly fails.

### ISSUE THREAD

**Issue by yhorndt** [sbraconnier/jodconverter#204]
Our jodconverter (jodconverter-local v4.2.2) randomly fails. It looks like it's a race condition.
```
2020-04-24 16:22:09,520 org.mule.api.processor.LoggerMessageProcessor - bfb591d9-18a9-4c88-b74e-6db1038c7fa5: Processing incoming PDFMessageRequest.
2020-04-24 16:22:09,557 org.mule.api.processor.LoggerMessageProcessor - bfb591d9-18a9-4c88-b74e-6db1038c7fa5: Converting / merging attachments...
2020-04-24 16:22:09,650 org.jodconverter.office.OfficeProcessManager - Submitting task 'Start' and waiting...
2020-04-24 16:22:09,696 [OfficeProcessThread-0] WARN  org.jodconverter.office.OfficeProcess - Profile dir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1' already exists; deleting
2020-04-24 16:22:09,772 org.mule.api.processor.LoggerMessageProcessor - 0e7920a2-823a-4442-98ec-c9b5359a51b3: Processing incoming PDFMessageRequest.
2020-04-24 16:22:09,774 org.mule.api.processor.LoggerMessageProcessor - 0e7920a2-823a-4442-98ec-c9b5359a51b3: Converting / merging attachments...
2020-04-24 16:22:09,776 org.jodconverter.office.OfficeProcessManager - Submitting task 'Start' and waiting...
2020-04-24 16:22:09,801 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2020-04-24 16:22:09,811 [OfficeProcessThread-1] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2020-04-24 16:22:10,244 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from help output): Product: LibreOffice - Version: 5.3.6.1 - useLongOptionNameGnuStyle: true
2020-04-24 16:22:10,244 [OfficeProcessThread-1] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from help output): Product: LibreOffice - Version: 5.3.6.1 - useLongOptionNameGnuStyle: true
2020-04-24 16:22:10,244 [OfficeProcessThread-1] INFO  org.jodconverter.office.OfficeProcess - Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2020-04-24 16:22:10,246 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeProcess - Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2020-04-24 16:22:10,295 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeProcess - Started process; pid = 31106
2020-04-24 16:22:10,295 [OfficeProcessThread-1] INFO  org.jodconverter.office.OfficeProcess - Started process; pid = 31106
2020-04-24 16:22:10,897 [OfficeProcessThread-0] WARN  org.jodconverter.office.ConnectRetryable - Office process died with exit code 81; restarting it
2020-04-24 16:22:10,921 [OfficeProcessThread-0] WARN  org.jodconverter.office.OfficeProcess - A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' is already running; pid 31106
2020-04-24 16:22:11,148 ERROR nl.xxx.template.Converter - Office process died with exit code 137
2020-04-24 16:22:11,291 nl.xxx.template.Converter - 0e7920a2-823a-4442-98ec-c9b5359a51b3: Now merging /var/www/html/Email.txt
2020-04-24 16:22:11,679 [[xxx_mule_domain]._GLOBAL_HTTP_Listener_Configuration.worker.02] ERROR org.mule.exception.DefaultMessagingExceptionStrategy -
********************************************************************************
Message               : This office manager is not running. (java.lang.IllegalStateException).
```
When it starts normally, it seems to start twice as well, but with different pids:
```
2020-04-24 16:33:17,280 [[xxx_mule_domain]._GLOBAL_HTTP_Listener_Configuration.worker.01] INFO  org.jodconverter.office.OfficeProcessManager - Submitting task 'Start' and waiting...
2020-04-24 16:33:17,330 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2020-04-24 16:33:17,471 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from help output): Product: LibreOffice - Version: 5.3.6.1 - useLongOptionNameGnuStyle: true
2020-04-24 16:33:17,471 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeProcess - Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2020-04-24 16:33:17,504 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeProcess - Started process; pid = 34552
2020-04-24 16:33:17,808 [OfficeProcessThread-0] WARN  org.jodconverter.office.ConnectRetryable - Office process died with exit code 81; restarting it
2020-04-24 16:33:17,840 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2020-04-24 16:33:18,022 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeDescriptor - soffice info (from help output): Product: LibreOffice - Version: 5.3.6.1 - useLongOptionNameGnuStyle: true
2020-04-24 16:33:18,022 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeProcess - Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2020-04-24 16:33:18,051 [OfficeProcessThread-0] INFO  org.jodconverter.office.OfficeProcess - Started process; pid = 34580
```

This happened 3-4 times over the last 2-3 months, with daily use of the converter.
Let me know if I can supply more information and what information. Thanks!

**Comment by sbraconnier** [comment]
Sorry for the delay. I'm really busy these day with the current situation (I work for a company serving health care facilities).

I'll need more information about your project to help you... It is a WEB application ??? Do you start the office manager for each conversion in a WEB app context ???

It is strange to see in your logs more than 1 LibreOffice startup on the same port, at the same time....

**Comment by DonaldY** [comment]
I meet same problem.

```
[INFO][9028395994469601] 2020-06-16 20:50:55.671 org.jodconverter.office.OfficeConnection:[200] - Disconnected: 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
[WARN][9028395994607591] 2020-06-16 20:50:55.671 org.jodconverter.office.OfficeProcessManagerPoolEntry:[93] - Connection lost unexpectedly; attempting restart
[INFO][9028395994710336] 2020-06-16 20:50:55.671 org.jodconverter.office.OfficeProcessManager:[203] - Executing task 'Restart After Lost Connection'...
[INFO][9028395994814555] 2020-06-16 20:50:55.672 org.jodconverter.office.OfficeProcessManager:[77] - process exited with code 137
[INFO][9028395999450732] 2020-06-16 20:50:55.676 org.jodconverter.office.OfficeConnection:[200] - Disconnected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
[WARN][9028395999559095] 2020-06-16 20:50:55.676 org.jodconverter.office.OfficeProcessManagerPoolEntry:[93] - Connection lost unexpectedly; attempting restart
[INFO][9028395999632375] 2020-06-16 20:50:55.676 org.jodconverter.office.OfficeProcessManager:[203] - Executing task 'Restart After Lost Connection'...
[INFO][9028395999913458] 2020-06-16 20:50:55.677 org.jodconverter.office.OfficeProcessManager:[77] - process exited with code 137
[INFO][9028396048446334] 2020-06-16 20:50:55.725 org.jodconverter.office.OfficeDescriptor:[97] - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[INFO][9028396056989884] 2020-06-16 20:50:55.734 org.jodconverter.office.OfficeDescriptor:[97] - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[INFO][9028396068212023] 2020-06-16 20:50:55.745 org.jodconverter.office.OfficeDescriptor:[97] - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[INFO][9028396173771524] 2020-06-16 20:50:55.850 org.jodconverter.office.OfficeDescriptor:[72] - soffice info (from help output): Product: LibreOffice - Version: 6.2.7.1 - useLongOptionNameGnuStyle: true
[INFO][9028396174020798] 2020-06-16 20:50:55.851 org.jodconverter.office.OfficeProcess:[395] - Starting process with acceptString 'socket,host=127.0.0.1,port=2004,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2004_tcpNoDelay-1'
[INFO][9028396179378556] 2020-06-16 20:50:55.856 org.jodconverter.office.OfficeDescriptor:[72] - soffice info (from help output): Product: LibreOffice - Version: 6.2.7.1 - useLongOptionNameGnuStyle: true
[INFO][9028396179568626] 2020-06-16 20:50:55.856 org.jodconverter.office.OfficeProcess:[395] - Starting process with acceptString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1'
[INFO][9028396191829473] 2020-06-16 20:50:55.869 org.jodconverter.office.OfficeDescriptor:[72] - soffice info (from help output): Product: LibreOffice - Version: 6.2.7.1 - useLongOptionNameGnuStyle: true
[INFO][9028396192032882] 2020-06-16 20:50:55.869 org.jodconverter.office.OfficeProcess:[395] - Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
[INFO][9028396241735873] 2020-06-16 20:50:55.918 org.jodconverter.office.OfficeProcess:[402] - Started process; pid = 796464
[INFO][9028396263430647] 2020-06-16 20:50:55.940 org.jodconverter.office.OfficeProcess:[402] - Started process; pid = 796474
[INFO][9028396289108908] 2020-06-16 20:50:55.966 org.jodconverter.office.OfficeProcess:[402] - Started process; pid = 796478
[ERROR][9028396497235161] 2020-06-16 20:50:56.174 org.jodconverter.office.OfficeProcessManager:[218] - Could not restart process after connection lost.
org.jodconverter.office.OfficeException: Office process died with exit code 137
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$2.run(OfficeProcessManager.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2004,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:170)
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
	... 8 common frames omitted
Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144)
	at com.sun.star.comp.connections.Connector.connect(Connector.java:119)
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:106)
	... 9 common frames omitted
[ERROR][9028396514817884] 2020-06-16 20:50:56.191 org.jodconverter.office.OfficeProcessManager:[218] - Could not restart process after connection lost.
org.jodconverter.office.OfficeException: Office process died with exit code 137
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$2.run(OfficeProcessManager.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by DonaldY** [comment]
> Sorry for the delay. I'm really busy these day with the current situation (I work for a company serving health care facilities).
> 
> I'll need more information about your project to help you... It is a WEB application ??? Do you start the office manager for each conversion in a WEB app context ???
> 
> It is strange to see in your logs more than 1 LibreOffice startup on the same port, at the same time....



> I meet same problem.
> 
> ```
> [INFO][9028395994469601] 2020-06-16 20:50:55.671 org.jodconverter.office.OfficeConnection:[200] - Disconnected: 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
> [WARN][9028395994607591] 2020-06-16 20:50:55.671 org.jodconverter.office.OfficeProcessManagerPoolEntry:[93] - Connection lost unexpectedly; attempting restart
> [INFO][9028395994710336] 2020-06-16 20:50:55.671 org.jodconverter.office.OfficeProcessManager:[203] - Executing task 'Restart After Lost Connection'...
> [INFO][9028395994814555] 2020-06-16 20:50:55.672 org.jodconverter.office.OfficeProcessManager:[77] - process exited with code 137
> [INFO][9028395999450732] 2020-06-16 20:50:55.676 org.jodconverter.office.OfficeConnection:[200] - Disconnected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
> [WARN][9028395999559095] 2020-06-16 20:50:55.676 org.jodconverter.office.OfficeProcessManagerPoolEntry:[93] - Connection lost unexpectedly; attempting restart
> [INFO][9028395999632375] 2020-06-16 20:50:55.676 org.jodconverter.office.OfficeProcessManager:[203] - Executing task 'Restart After Lost Connection'...
> [INFO][9028395999913458] 2020-06-16 20:50:55.677 org.jodconverter.office.OfficeProcessManager:[77] - process exited with code 137
> [INFO][9028396048446334] 2020-06-16 20:50:55.725 org.jodconverter.office.OfficeDescriptor:[97] - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
> [INFO][9028396056989884] 2020-06-16 20:50:55.734 org.jodconverter.office.OfficeDescriptor:[97] - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
> [INFO][9028396068212023] 2020-06-16 20:50:55.745 org.jodconverter.office.OfficeDescriptor:[97] - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
> [INFO][9028396173771524] 2020-06-16 20:50:55.850 org.jodconverter.office.OfficeDescriptor:[72] - soffice info (from help output): Product: LibreOffice - Version: 6.2.7.1 - useLongOptionNameGnuStyle: true
> [INFO][9028396174020798] 2020-06-16 20:50:55.851 org.jodconverter.office.OfficeProcess:[395] - Starting process with acceptString 'socket,host=127.0.0.1,port=2004,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2004_tcpNoDelay-1'
> [INFO][9028396179378556] 2020-06-16 20:50:55.856 org.jodconverter.office.OfficeDescriptor:[72] - soffice info (from help output): Product: LibreOffice - Version: 6.2.7.1 - useLongOptionNameGnuStyle: true
> [INFO][9028396179568626] 2020-06-16 20:50:55.856 org.jodconverter.office.OfficeProcess:[395] - Starting process with acceptString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1'
> [INFO][9028396191829473] 2020-06-16 20:50:55.869 org.jodconverter.office.OfficeDescriptor:[72] - soffice info (from help output): Product: LibreOffice - Version: 6.2.7.1 - useLongOptionNameGnuStyle: true
> [INFO][9028396192032882] 2020-06-16 20:50:55.869 org.jodconverter.office.OfficeProcess:[395] - Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
> [INFO][9028396241735873] 2020-06-16 20:50:55.918 org.jodconverter.office.OfficeProcess:[402] - Started process; pid = 796464
> [INFO][9028396263430647] 2020-06-16 20:50:55.940 org.jodconverter.office.OfficeProcess:[402] - Started process; pid = 796474
> [INFO][9028396289108908] 2020-06-16 20:50:55.966 org.jodconverter.office.OfficeProcess:[402] - Started process; pid = 796478
> [ERROR][9028396497235161] 2020-06-16 20:50:56.174 org.jodconverter.office.OfficeProcessManager:[218] - Could not restart process after connection lost.
> org.jodconverter.office.OfficeException: Office process died with exit code 137
> 	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
> 	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
> 	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
> 	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
> 	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
> 	at org.jodconverter.office.OfficeProcessManager$2.run(OfficeProcessManager.java:215)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2004,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
> 	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:170)
> 	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
> 	... 8 common frames omitted
> Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
> 	at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144)
> 	at com.sun.star.comp.connections.Connector.connect(Connector.java:119)
> 	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:106)
> 	... 9 common frames omitted
> [ERROR][9028396514817884] 2020-06-16 20:50:56.191 org.jodconverter.office.OfficeProcessManager:[218] - Could not restart process after connection lost.
> org.jodconverter.office.OfficeException: Office process died with exit code 137
> 	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
> 	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
> 	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
> 	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
> 	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
> 	at org.jodconverter.office.OfficeProcessManager$2.run(OfficeProcessManager.java:215)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

web application.  @sbraconnier

**Comment by yhorndt** [comment]
Our problem is fixed right now. We have done a refactor of our code, which used to start two instances on some occasions.

**Comment by sbraconnier** [comment]
@yhorndt Thanks for you findings... 

@DonaldY Do you still have your problem ?

**Comment by jhuamanchumo** [comment]
Hi, I'm having the same issue sometimes, I have a spring boot app that runs in a docker container, I have the jodconverter-local dependency in the pom.xml of my app, then I have a method that calls JodConverter each time is needed, I supose that this is not a best practice, maybe you can help me with the best way to do this, I think this method is called 1k times a day.

```
public class PDFUtil {
   public static void doConvert(File wordInput, File pdfOutput) throws OfficeException {
		final LocalOfficeManager officeManager = LocalOfficeManager.install();
		officeManager.start();
		JodConverter.convert(wordInput).to(pdfOutput).execute();
		OfficeUtils.stopQuietly(officeManager);
	}
}
```

**Comment by sbraconnier** [comment]
Maybe you could use the [jodconverter-spring-boot-starter](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-spring-boot-starter) starter ? Your implementation will start an office process for each conversion. You will notice a BIG performance improvement if you use the jodconverter starter.

[Here's a sample project](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-spring-boot) that uses the jodconverter starter.

**Comment by sbraconnier** [comment]
[This](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) sample also uses the jodconverter starter.

**Comment by jhuamanchumo** [comment]
@sbraconnier thanks for response, I will try this out, would you recommend for bulk document convertion : creating an isolated docker container (or isolated microservice) for converting and access using the rest api or  include this logic into existing spring-boot app.

**Comment by sbraconnier** [comment]
It really depends on your whole big picture... I would not do that if the use of jodconverter would introduce the complexity of a single microservice/isolated docker container. But if you are already using such an infrastructure for other things, it could be a good idea for consistency (among other things).

I tend to keep things simple, until more than 1 "application" need the same thing or need to share something !! I recently had to extract the "data" logic of an application to make it accessible to more than 1 application. But everything worked fine for more than 5 years without this. So, for a (small) company point of view, not doing the perfect thing first was the good thing to do. 

But that's just me. I'm sure you will be able to decide what's best for you according to what you have to deal with (your company, skills, etc...).

**Comment by sbraconnier** [comment]
Closing this one. Feel free to reopen if needed!
