### ISSUE TITLE
JodConverter Not able to start LibreOffice process on AmazonCorretto 

### ISSUE THREAD

**Issue by OsamaAnwer** [sbraconnier/jodconverter#206]
Hi I am unable to use jodconverter on amazon corretto 11 (docker image). I am able to convert documents through cli on the same instance, which means soffice executable is working fine.

Also, the same code is working perfectly fine on OSX.

**Stack trace with some logs:**

```
[jodconverter-officeprocess-8] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[jodconverter-officeprocess-8] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from help output): Product: LibreOffice - Version: 6.3.5.2 - useLongOptionNameGnuStyle: true
[jodconverter-officeprocess-8] INFO org.jodconverter.local.office.OfficeProcess - OFFICE HOME: /opt/libreoffice6.3
[jodconverter-officeprocess-8] INFO org.jodconverter.local.office.OfficeProcess - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
[jodconverter-officeprocess-8] WARN org.jodconverter.local.office.StartProcessRetryable - Office process died with exit code 81; restarting it
org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager'
	at org.jodconverter.local.office.OfficeProcess.start(OfficeProcess.java:442)
	at org.jodconverter.local.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:145)
	at org.jodconverter.local.office.OfficeProcessManager.lambda$startAndWait$3(OfficeProcessManager.java:287)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jodconverter.core.office.RetryTimeoutException
	at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:81)
	at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:52)
	at org.jodconverter.local.office.OfficeProcess.start(OfficeProcess.java:430)
	at org.jodconverter.local.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:145)
	at org.jodconverter.local.office.OfficeProcessManager.lambda$startAndWait$3(OfficeProcessManager.java:287)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

OS information: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/what-is-corretto-11.html

I am using version `4.3.0` of JodConverter.

Sample code being used:
```
 officeManager = LocalOfficeManager.builder()
                    .officeHome(LIBRE_OFFICE_HOME)
                    .install()
                    .build();
//Exception occurred below.. 
officeManager.start();
```

**Comment by OsamaAnwer** [comment]
@sbraconnier, could you please take a look into this?

**Comment by NABEEL-AHMED-JAMIL** [comment]
can you pls share image?

**Comment by sbraconnier** [comment]
It is strange... It is suppose to work. Maybe you could take a look [here](https://github.com/EugenMayer/docker-image-jodconverter). I know that this docker works properly. I myself am not that familiar with Docker (on my todo list for quite some time).

**Comment by NABEEL-AHMED-JAMIL** [comment]
Try this one
```
#Building Docker Image for Patent Master
FROM amazonlinux:latest

# Install OpenJDK-8
RUN yum install -y java-1.8.0-openjdk;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.*.x86_64/
RUN export JAVA_HOME

#Install libreoffice
RUN amazon-linux-extras install libreoffice

#Install procps package for ps commands
RUN yum install -y procps

#Set locale to utf8
ENV LC_ALL en_US.UTF-8

ADD target/your-jar-path.jar app.jar
ENTRYPOINT ["java","-Dfile.encoding=UTF-8","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]
```

**Comment by NABEEL-AHMED-JAMIL** [comment]
Try this too
```
FROM maven:3.6.1-jdk-8
ADD yourjar.jar app.jar
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar", "app.jar"]

RUN apt-get update; \
    apt-get install -y --no-install-recommends libreoffice; \
    rm -rf /var/lib/apt/lists/*

EXPOSE 9099
```

**Comment by OsamaAnwer** [comment]
Thanks for responding @NABEEL-AHMED-JAMIL, were you able to reproduce the issue?

**Comment by OsamaAnwer** [comment]
@sbraconnier thanks for responding, https://github.com/EugenMayer/docker-image-jodconverter
This doesn't fit to our requirement, since we dont need a RESTful solution. 

The exception seems to be appearing from here:
https://github.com/sbraconnier/jodconverter/blob/0dbddecddd690035eaa7b89ed5a2b9bda1172a6a/jodconverter-local/src/main/java/org/jodconverter/local/office/ConnectRetryable.java#L88-L94

**Comment by sbraconnier** [comment]
Yeah, this rings a bell.... 

If you look [here](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/office/StartProcessRetryable.java#L87), I had to do something special when starting an office process on FreeBSD. Your problem looks very similar.... Maybe I could add a condition for  amazon corretto too.

Would you be able to create a fork of the problem to see if it could solve your issue ??

**Comment by sbraconnier** [comment]
@NABEEL-AHMED-JAMIL I just want to thank you to help me answering question! It is really appreciated!!! :pray::smiley::open_hands:

**Comment by OsamaAnwer** [comment]
@sbraconnier, sure i'll test and let you know.

**Comment by DamienFontaine** [comment]
Same error. Fixed with 
`
RUN apt-get intall procps
`

**Comment by sbraconnier** [comment]
Wow, thanks @DamienFontaine

**Comment by sbraconnier** [comment]
@OsamaAnwer Does the @DamienFontaine comment helped you ??

**Comment by sbraconnier** [comment]
Will close this one due to inactivity. Fell free to re-open is needed.

**Comment by MisterKrab** [comment]
> Same error. Fixed with `RUN apt-get intall procps`

It's awesome 👍

**Comment by keyleaf** [comment]
> Same error. Fixed with `RUN apt-get intall procps`

u r the hero!
