### ISSUE TITLE
Depending on the operating system, /tmp is getting regularly cleaned

### ISSUE THREAD

**Issue by vinz243** [sbraconnier/jodconverter#220]
I'm using jodconverter local on CentOS, and I have been getting FileNotFoundException :

```
Caused by: org.jodconverter.job.DocumentSpecsIOException: Could not write stream to file /tmp/jodconverter_d99a2a90-aec4-49e6-
at org.jodconverter.job.SourceDocumentSpecsFromInputStream.getFile(SourceDocumentSpecsFromInputStream.java:72) ~[jodconverter-
at org.jodconverter.task.LocalConversionTask.execute(LocalConversionTask.java:96) ~[jodconverter-local-4.2.2.jar!/:4.2.2]
at org.jodconverter.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:148) ~[jodconverter-loca
at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:77) ~[jodconverter-core-4
at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:73) ~[jodconverter-core-4
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
... 3 more
Caused by: java.io.FileNotFoundException: /tmp/jodconverter_d99a2a90-aec4-49e6-a4c5-6428b93d70ba/tempfile_2.odt (Aucun fichier
at java.io.FileOutputStream.open0(Native Method) ~[?:?]
at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
at org.jodconverter.job.SourceDocumentSpecsFromInputStream.getFile(SourceDocumentSpecsFromInputStream.java:62) ~[jodconverter-
at org.jodconverter.task.LocalConversionTask.execute(LocalConversionTask.java:96) ~[jodconverter-local-4.2.2.jar!/:4.2.2]
at org.jodconverter.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:148) ~[jodconverter-loca
at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:77) ~[jodconverter-core-4
at org.jodconverter.office.AbstractOfficeManagerPoolEntry$1.call(AbstractOfficeManagerPoolEntry.java:73) ~[jodconverter-core-4
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
... 3 more
```

After investigation, it turns out [CentOS 7 automatically cleans up /tmp directory periodically](https://www.thegeekdiary.com/centos-rhel-67-why-the-files-in-tmp-directory-gets-deleted-periodically/). 

However, Jodconverter doesn't take that into account and if it's been started for a few hours and not used, the following conversion jobs will fail with the FNFE. 

This can be fixed from our end, by specifying another working directory. But I think it could also either mkdir the directory every time to avoid those errors or at least some disclaimer should be brought forward to inform other users.

**Comment by sbraconnier** [comment]
Hi there. The working directory is used when creating 2 important directories:

- The temp directory used by jodconverter, when we have to deal with streams (convert from/to streams).
- The instance profile directory, that must be unique per office instances (created by the office process on start).

I could probably re-create the temp directory each time it is used if it doesn't exist, but I would strongly recommend to use another working directory if the default one is "cleaned" automatically by an automated process.

The instance profile directory is created by the office process when it is started, not by jodconverter. I guess that when the working directory is automatically cleaned, it fails on that particular directory since it is used by another process. But it looks risky to me to let an automated process try to delete this directory. Not sure where to put the disclaimer... [Here](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_folderworkingdir) maybe ?

**Comment by vinz243** [comment]
I was thinking about the temp directory. 

> I could probably re-create the temp directory each time it is used if it doesn't exist, but I would strongly recommend to use another working directory if the default one is "cleaned" automatically by an automated process.

That's what I did anyway. Documenting this on the configuration page seems good, with that and this issue it should be enough for people who could encounter this issue in the future

**Comment by sbraconnier** [comment]
The documentation has been [updated](https://github.com/sbraconnier/jodconverter/issues/220)
