### ISSUE TITLE
org.jodconverter.core.office.OfficeException: Could not store document:  errorCode: 2074

### ISSUE THREAD

**Issue by zhangjunp** [sbraconnier/jodconverter#239]
when i use openOffice convert html to doc or pdf  ,it's throws exception
`
 @Resource
    private DocumentConverter converter;

    @Override
    public void convert(MultipartFile inputFile,File file,String outputFormat){
        final DocumentFormat targetFormat =
                DefaultDocumentFormatRegistry.getFormatByExtension(outputFormat);
        assert targetFormat != null;
        try {
            converter.convert(inputFile.getInputStream()).as(targetFormat).to(file).execute();
        } catch (OfficeException | IOException e) {
            log.error("Doc2Other ex:",e);
        }
    }
`
throws exception:
`org.jodconverter.core.office.OfficeException: Could not store document: c08721a125d94984995be41f2b58962a.doc; errorCode: 2074
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:183) ~[jodconverter-local-4.3.0.jar!/:4.3.0]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:119) ~[jodconverter-local-4.3.0.jar!/:4.3.0]
	at org.jodconverter.local.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:187) ~[jodconverter-local-4.3.0.jar!/:4.3.0]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:83) ~[jodconverter-core-4.3.0.jar!/:4.3.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

**Comment by whh1009** [comment]
我也碰到了同样的问题，不知道如何解决

**Comment by zhangjunp** [comment]
可能是因为格式不支持导致的… 你可以看一下kkfileview这个开源框架


| |
zjp20123258
邮箱：zjp20123258@163.com
|

Signature is customized by Netease Mail Master

On 12/24/2020 17:30, whh wrote:

我也碰到了同样的问题，不知道如何解决

**Comment by sbraconnier** [comment]
Could you please try with LibreOffice and let me know if it works ?

It seems to be a problem with LO/OO that has been fixed over time:
https://github.com/unoconv/unoconv/issues/18

**Comment by sbraconnier** [comment]
Will close this one due to inactivity. Fell free to re-open is needed.
