### ISSUE TITLE
LibreOffice not starting when run from Systemd / tomcat user

### ISSUE THREAD

**Issue by kn1ght0wl** [sbraconnier/jodconverter#240]
We are running Xwiki 12.9 on Ubuntu 18.04.5 LTS (Bionic Beaver). After installing LibreOffice `apt-get install libreoffice` version: 1:6.0.7-0ubuntu0.18.04.10 and enabling it in the conf, restarting Tomcat9 produces the error:

> Error while connecting / starting the office server.

Originally I found that LibreOffice was trying to write to the tomcat home directory, so I added `ReadWritePaths=/local/home/tomcat` to `/etc/systemd/system/tomcat9.service.d/xwiki-tomcat9-systemd.conf`, and after configuring the tomcat home dir, resolved that issue. However, I still cannot get it to start. If I run tomcat (Xwiki) as root it works, but starting it from systemd (tomcat user) fails.

From catalina.out, one message stands out: 

> Office process died with exit code 77

Full error:
```
2020-12-09 13:20:56,304 [main] ERROR .OfficeServerLifecycleListener - Error while connecting / starting the office server.
org.xwiki.officeimporter.server.OfficeServerException: Error while connecting / starting the office server.
at org.xwiki.officeimporter.internal.server.DefaultOfficeServer.start(DefaultOfficeServer.java:208)
at org.xwiki.officeimporter.internal.server.OfficeServerLifecycleListener.startOfficeServer(OfficeServerLifecycleListener.java:98)
at org.xwiki.officeimporter.internal.server.OfficeServerLifecycleListener.onEvent(OfficeServerLifecycleListener.java:85)
at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:320)
at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:285)
at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:337)
at org.xwiki.container.servlet.XWikiServletContextListener.contextInitialized(XWikiServletContextListener.java:127)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4668)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5136)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1832)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1577)
at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:929)
at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:928)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
at org.apache.catalina.startup.Catalina.start(Catalina.java:638)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:496)
Caused by: org.jodconverter.office.OfficeException: Office process died with exit code 77
at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:76)
at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
at org.jodconverter.office.OfficeProcessManager.lambda$startAndWait$3(OfficeProcessManager.java:243)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: ‘socket,host=127.0.0.1,port=8100,tcpNoDelay=1’; java.net.ConnectException: Connection refused (Connection refused)
at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:172)
at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
… 8 common frames omitted
Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144)
at com.sun.star.comp.connections.Connector.connect(Connector.java:119)
at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:106)
… 9 common frames omitted
```

**Comment by kn1ght0wl** [comment]
Was able to generate more log messages for the issue tonight:

`[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,270 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] INFO  .j.o.AbstractOfficeManagerPool - Stopping the office manager pool...
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,273 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] INFO  o.j.o.OfficeProcessManager     - Submitting task 'Stop' and waiting...
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,277 [OfficeProcessThread-0] DEBUG o.j.o.OfficeProcessManager     - Exception catched in doStopProcess
[2020-12-11 00:36:38] [info] java.lang.NullPointerException: null
[2020-12-11 00:36:38] [info] #011at org.jodconverter.office.OfficeProcessManager.doStopProcess(OfficeProcessManager.java:128)
[2020-12-11 00:36:38] [info] #011at org.jodconverter.office.OfficeProcessManager.lambda$stopAndWait$4(OfficeProcessManager.java:259)
[2020-12-11 00:36:38] [info] #011at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2020-12-11 00:36:38] [info] #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2020-12-11 00:36:38] [info] #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2020-12-11 00:36:38] [info] #011at java.base/java.lang.Thread.run(Thread.java:834)
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,277 [OfficeProcessThread-0] INFO  o.j.o.OfficeProcess            - Trying to forcibly terminate process: 'host=127.0.0.1,port=8100,tcpNoDelay=1'; pid: 32551
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,288 [OfficeProcessThread-0] TRACE o.j.p.AbstractProcessManager   - Command Error: kill: (32551): No such process
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,289 [OfficeProcessThread-0] INFO  o.j.o.OfficeProcessManager     - Process terminated with code 77
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,289 [OfficeProcessThread-0] INFO  o.j.o.OfficeProcessManager     - Process exited with code 77
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,289 [OfficeProcessThread-0] DEBUG o.j.o.OfficeProcess            - Deleting instance profile directory '/tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,299 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] DEBUG o.j.o.OfficeProcessManager     - Task executed successfully: Stop
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,299 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] INFO  o.j.o.OfficeProcessManager     - Submitting task 'Stop' and waiting...
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,304 [OfficeProcessThread-1] DEBUG o.j.o.OfficeProcessManager     - Exception catched in doStopProcess
[2020-12-11 00:36:38] [info] java.lang.NullPointerException: null
[2020-12-11 00:36:38] [info] #011at org.jodconverter.office.OfficeProcessManager.doStopProcess(OfficeProcessManager.java:128)
[2020-12-11 00:36:38] [info] #011at org.jodconverter.office.OfficeProcessManager.lambda$stopAndWait$4(OfficeProcessManager.java:259)
[2020-12-11 00:36:38] [info] #011at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2020-12-11 00:36:38] [info] #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2020-12-11 00:36:38] [info] #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2020-12-11 00:36:38] [info] #011at java.base/java.lang.Thread.run(Thread.java:834)
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,305 [OfficeProcessThread-1] INFO  o.j.o.OfficeProcessManager     - Process terminated with code 0
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,305 [OfficeProcessThread-1] INFO  o.j.o.OfficeProcessManager     - Process exited with code 0
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,305 [OfficeProcessThread-1] DEBUG o.j.o.OfficeProcess            - Deleting instance profile directory '/tmp/.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1'
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,306 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] DEBUG o.j.o.OfficeProcessManager     - Task executed successfully: Stop
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,307 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] INFO  .j.o.AbstractOfficeManagerPool - Office manager stopped
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,307 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] INFO  o.x.o.i.s.DefaultOfficeServer  - Open Office instance stopped.
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,313 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] INFO  o.j.o.OfficeProcessManager     - Submitting task 'Start' and waiting...
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,314 [OfficeProcessThread-2] TRACE o.j.p.AbstractProcessManager   - Finding PID using
[2020-12-11 00:36:38] [info] Command to get current running processes: [/bin/sh, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
[2020-12-11 00:36:38] [info] Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
[2020-12-11 00:36:38] [info] Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,333 [OfficeProcessThread-2] DEBUG o.j.p.AbstractProcessManager   - No matching command line found! Returning pid: NOT_FOUND
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,334 [OfficeProcessThread-2] DEBUG o.j.o.OfficeProcess            - Checking existing process done successfully. No process running with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager'
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,334 [OfficeProcessThread-2] INFO  o.j.o.OfficeDescriptor         - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,625 [OfficeProcessThread-2] DEBUG o.j.o.OfficeDescriptor         - Building org.jodconverter.office.OfficeDescriptor from help output lines
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,626 [OfficeProcessThread-2] INFO  o.j.o.OfficeDescriptor         - soffice info (from help output): Product: LibreOffice - Version: 6.0.7.3 - useLongOptionNameGnuStyle: true
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,627 [OfficeProcessThread-2] DEBUG o.j.o.OfficeProcess            - ProcessBuilder command: /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,627 [OfficeProcessThread-2] INFO  o.j.o.OfficeProcess            - OFFICE HOME: /usr/lib/libreoffice
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,627 [OfficeProcessThread-2] INFO  o.j.o.OfficeProcess            - Starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,633 [OfficeProcessThread-2] DEBUG o.j.o.StartProcessRetryable    - Trying to find pid, attempt #1
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,634 [OfficeProcessThread-2] TRACE o.j.p.AbstractProcessManager   - Finding PID using
[2020-12-11 00:36:38] [info] Command to get current running processes: [/bin/sh, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
[2020-12-11 00:36:38] [info] Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
[2020-12-11 00:36:38] [info] Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,665 [OfficeProcessThread-2] TRACE o.j.p.AbstractProcessManager   - Command Output:  1447 /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,665 [OfficeProcessThread-2] TRACE o.j.p.AbstractProcessManager   - Checking if process line matches the process line regex
[2020-12-11 00:36:38] [info] Process line:  1447 /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,665 [OfficeProcessThread-2] TRACE o.j.p.AbstractProcessManager   - Line matches!
[2020-12-11 00:36:38] [info] pid: 1447; Command line: /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1
[2020-12-11 00:36:38] [info] Checking if this command line matches the office command line regex
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,665 [OfficeProcessThread-2] DEBUG o.j.p.AbstractProcessManager   - Command line matches! Returning pid: 1447
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,665 [OfficeProcessThread-2] INFO  o.j.o.OfficeProcess            - Started process; pid: 1447
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,666 [OfficeProcessThread-2] DEBUG o.j.o.OfficeConnection         - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,667 [OfficeProcessThread-2] TRACE o.j.o.OfficeConnection         - Connector created successfully, trying to connect...
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,676 [OfficeProcessThread-2] TRACE o.j.o.VerboseProcess           - The Office process has not yet terminated.
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,927 [OfficeProcessThread-2] DEBUG o.j.o.OfficeConnection         - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,928 [OfficeProcessThread-2] TRACE o.j.o.OfficeConnection         - Connector created successfully, trying to connect...
[2020-12-11 00:36:38] [info] 2020-12-11 00:36:38,929 [OfficeProcessThread-2] TRACE o.j.o.VerboseProcess           - The Office process has not yet terminated.
[2020-12-11 00:36:39] [info] 2020-12-11 00:36:39,180 [OfficeProcessThread-2] DEBUG o.j.o.OfficeConnection         - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
[2020-12-11 00:36:39] [info] 2020-12-11 00:36:39,181 [OfficeProcessThread-2] TRACE o.j.o.OfficeConnection         - Connector created successfully, trying to connect...
[2020-12-11 00:36:39] [info] 2020-12-11 00:36:39,186 [http-nio-8080-exec-5 - http://itwikidev.sungardas.corp/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] DEBUG o.j.o.OfficeProcessManager     - ExecutionException catched in submitAndWait for task: Start
[2020-12-11 00:36:39] [info] java.util.concurrent.ExecutionException: org.jodconverter.office.OfficeException: Office process died with exit code 77`

**Comment by sbraconnier** [comment]
I there. Sorry for the delay. Not sure if you found your issue but it seems to be related to a permission restriction. It is you or xwiki that is responsible to deal with jodconverter ? I'm not familiar with xwiki, but jodconverter can start libreoffice with the sudo argument. Take a look [here](https://github.com/sbraconnier/jodconverter/issues/189)

**Comment by sbraconnier** [comment]
Will close this one due to inactivity. Fell free to re-open if needed.
