### ISSUE TITLE
org.jodconverter.office.OfficeException: Office process died with exit code 333

### ISSUE THREAD

**Issue by lcygames** [sbraconnier/jodconverter#268]
I am new to jodconverter for openoffice, i am facing issue while converting docx to pdf.

code:

`officeManager = LocalOfficeManager.builder()
                .install()
                .portNumbers(portNumber)
                .officeHome(getOfficeHome())
                .build();`

response:
`org.jodconverter.office.OfficeException: Office process died with exit code 333
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:261)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:256)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; java.net.ConnectException: Connection refused: connect
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:170)
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
	... 10 more
Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused: connect
	at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144)
	at com.sun.star.comp.connections.Connector.connect(Connector.java:119)
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:106)
	... 11 more`

        <dependency>
            <groupId>org.openoffice</groupId>
            <artifactId>juh</artifactId>
            <version>4.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.openoffice</groupId>
            <artifactId>unoil</artifactId>
            <version>4.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-core</artifactId>
            <version>4.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-local</artifactId>
            <version>4.2.2</version>
        </dependency>

OpenOffice Version : Apache_OpenOffice_4.1.10_Win_x86

**Comment by sbraconnier** [comment]
Could you please test with LibreOffice and let me know the result ? I need to know if the problem is with JODConverter or with Apache OpenOffice.

**Comment by lcygames** [comment]
I got the same result with LibreOffice

**Comment by sbraconnier** [comment]
Sorry for the long delay. I was quite busy this past year. Is this issue still relevant?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
