### ISSUE TITLE
"Unspecified Application Error" occurs from specific PPTX document

### ISSUE THREAD

**Issue by lesterlaucn** [sbraconnier/jodconverter#272]
I tried Linux and macOS，following is  error messages

pom.xml
```xml
 <dependency>
      <groupId>org.jodconverter</groupId>
      <artifactId>jodconverter-local</artifactId>
      <version>4.4.2</version>
  </dependency>
```

Libreoffice version: 7.2 and 6.3

-------------------
2021-11-03 10:11:28.697 [jodconverter-poolentry-1] INFO  org.jodconverter.local.task.LocalConversionTask.execute:93 -Executing local conversion task [doc -> pdf]...
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -Unspecified Application Error
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -Fatal exception: Signal 6
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -Stack:
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -0   libuno_sal.dylib.3                  0x000000010ce41d31 _ZN12_GLOBAL__N_110printStackEi + 49
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -1   libuno_sal.dylib.3                  0x000000010ce4e382 _ZN12_GLOBAL__N_121signalHandlerFunctionEiP9__siginfoPv.cold.1 + 34
2021-11-03 10:11:29.539 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -2   libuno_sal.dylib.3                  0x000000010ce41c23 _ZN12_GLOBAL__N_121signalHandlerFunctionEiP9__siginfoPv + 691
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -3   libsystem_platform.dylib            0x00007fff20482d7d _sigtramp + 29
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -4   ???                                 0x0000700007274960 0x0 + 123145422326112
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -5   libsystem_c.dylib                   0x00007fff20392406 abort + 125
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -6   libvcllo.dylib                      0x000000010fef9777 _Z8SalAbortRKN3rtl8OUStringEb + 119
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -7   libvcllo.dylib                      0x000000010fdd5931 _ZN11Application5AbortERKN3rtl8OUStringE + 193
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -8   libsofficeapp.dylib                 0x000000010ce8a512 _ZN7desktop7Desktop9ExceptionE17ExceptionCategory + 194
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -9   libvcllo.dylib                      0x000000010fddee8a _ZL23VCLExceptionSignal_implPvP13oslSignalInfo + 202
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -10  libuno_sal.dylib.3                  0x000000010ce129f9 _Z17callSignalHandlerP13oslSignalInfo + 41
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -11  libuno_sal.dylib.3                  0x000000010ce419c1 _ZN12_GLOBAL__N_121signalHandlerFunctionEiP9__siginfoPv + 81
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -12  libsystem_platform.dylib            0x00007fff20482d7d _sigtramp + 29
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -13  ???                                 0x0000000000000004 0x0 + 4
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -14  libooxlo.dylib                      0x00000001c1777da2 _ZThn64_N3oox9drawingml18Transform2DContext15onCreateContextEiRKNS_13AttributeListE + 18
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -15  libooxlo.dylib                      0x00000001c165c325 _ZN3oox4core21ContextHandler2Helper22implCreateChildContextEiRKN3com3sun4star3uno9ReferenceINS4_3xml3sax18XFastAttributeListEEE + 85
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -16  libooxlo.dylib                      0x00000001c165cb32 _ZThn40_N3oox4core15ContextHandler222createFastChildContextEiRKN3com3sun4star3uno9ReferenceINS4_3xml3sax18XFastAttributeListEEE + 18
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -17  libexpwraplo.dylib                  0x000000011cf56c41 _ZN12_GLOBAL__N_16Entity12startElementEPKNS_5EventE + 641
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -18  libexpwraplo.dylib                  0x000000011cf51d4a _ZN14sax_fastparser17FastSaxParserImpl11parseStreamERKN3com3sun4star3xml3sax11InputSourceE + 3658
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -19  libooxlo.dylib                      0x00000001c165e74b _ZN3oox4core10FastParser11parseStreamERKN3com3sun4star3xml3sax11InputSourceEb + 75
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -20  libooxlo.dylib                      0x00000001c165e949 _ZN3oox4core10FastParser11parseStreamERKN3com3sun4star3uno9ReferenceINS4_2io12XInputStreamEEERKN3rtl8OUStringE + 153
2021-11-03 10:11:29.540 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -21  libooxlo.dylib                      0x00000001c1674eaf _ZN3oox4core13XmlFilterBase14importFragmentERKN3rtl9ReferenceINS0_15FragmentHandlerEEERNS0_10FastParserE + 735
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -22  libooxlo.dylib                      0x00000001c1674b84 _ZN3oox4core13XmlFilterBase14importFragmentERKN3rtl9ReferenceINS0_15FragmentHandlerEEE + 68
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -23  libooxlo.dylib                      0x00000001c1841594 _ZN3oox3ppt20PPTShapeGroupContext17importExtDrawingsEv + 228
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -24  libooxlo.dylib                      0x00000001c165ccc1 _ZThn40_N3oox4core15ContextHandler214endFastElementEi + 49
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -25  libexpwraplo.dylib                  0x000000011cf57015 _ZN12_GLOBAL__N_16Entity10endElementEv + 69
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -26  libexpwraplo.dylib                  0x000000011cf51d62 _ZN14sax_fastparser17FastSaxParserImpl11parseStreamERKN3com3sun4star3xml3sax11InputSourceE + 3682
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -27  libooxlo.dylib                      0x00000001c165e74b _ZN3oox4core10FastParser11parseStreamERKN3com3sun4star3xml3sax11InputSourceEb + 75
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -28  libooxlo.dylib                      0x00000001c165e949 _ZN3oox4core10FastParser11parseStreamERKN3com3sun4star3uno9ReferenceINS4_2io12XInputStreamEEERKN3rtl8OUStringE + 153
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -29  libooxlo.dylib                      0x00000001c1674eaf _ZN3oox4core13XmlFilterBase14importFragmentERKN3rtl9ReferenceINS0_15FragmentHandlerEEERNS0_10FastParserE + 735
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -30  libooxlo.dylib                      0x00000001c1674b84 _ZN3oox4core13XmlFilterBase14importFragmentERKN3rtl9ReferenceINS0_15FragmentHandlerEEE + 68
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -31  libooxlo.dylib                      0x00000001c1846eb4 _ZN3oox3ppt27PresentationFragmentHandler11importSlideERKN3rtl9ReferenceINS_4core15FragmentHandlerEEERKNSt3__110shared_ptrINS0_12SlidePersistEEE + 1668
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -32  libooxlo.dylib                      0x00000001c184508b _ZN3oox3ppt27PresentationFragmentHandler11importSlideEjbb + 3675
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -33  libooxlo.dylib                      0x00000001c184745e _ZN3oox3ppt27PresentationFragmentHandler14finalizeImportEv + 862
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -34  libexpwraplo.dylib                  0x000000011cf51eed _ZN14sax_fastparser17FastSaxParserImpl11parseStreamERKN3com3sun4star3xml3sax11InputSourceE + 4077
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -35  libooxlo.dylib                      0x00000001c165e74b _ZN3oox4core10FastParser11parseStreamERKN3com3sun4star3xml3sax11InputSourceEb + 75
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -36  libooxlo.dylib                      0x00000001c165e949 _ZN3oox4core10FastParser11parseStreamERKN3com3sun4star3uno9ReferenceINS4_2io12XInputStreamEEERKN3rtl8OUStringE + 153
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -37  libooxlo.dylib                      0x00000001c1674eaf _ZN3oox4core13XmlFilterBase14importFragmentERKN3rtl9ReferenceINS0_15FragmentHandlerEEERNS0_10FastParserE + 735
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -38  libooxlo.dylib                      0x00000001c1674b84 _ZN3oox4core13XmlFilterBase14importFragmentERKN3rtl9ReferenceINS0_15FragmentHandlerEEE + 68
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -39  libooxlo.dylib                      0x00000001c183b0b6 _ZN3oox3ppt16PowerPointImport14importDocumentEv + 534
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -40  libooxlo.dylib                      0x00000001c166186f _ZN3oox4core10FilterBase6filterERKN3com3sun4star3uno8SequenceINS4_5beans13PropertyValueEEE + 783
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -41  libooxlo.dylib                      0x00000001c183b88d _ZN3oox3ppt16PowerPointImport6filterERKN3com3sun4star3uno8SequenceINS4_5beans13PropertyValueEEE + 45
2021-11-03 10:11:29.541 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -42  libsfxlo.dylib                      0x000000010ddfffe4 _ZN14SfxObjectShell10ImportFromER9SfxMediumRKN3com3sun4star3uno9ReferenceINS4_4text10XTextRangeEEE + 2596
2021-11-03 10:11:29.542 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -43  libsdlo.dylib                       0x00000001c23c4a8b _ZN2sd12DrawDocShell10ImportFromER9SfxMediumRKN3com3sun4star3uno9ReferenceINS5_4text10XTextRangeEEE + 251
2021-11-03 10:11:29.542 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -44  libsfxlo.dylib                      0x000000010ddf6bf7 _ZN14SfxObjectShell6DoLoadEP9SfxMedium + 4711
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -45  libsfxlo.dylib                      0x000000010de2577c _ZN12SfxBaseModel4loadERKN3com3sun4star3uno8SequenceINS2_5beans13PropertyValueEEE + 748
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -46  libsfxlo.dylib                      0x000000010deafc43 _ZN12_GLOBAL__N_119SfxFrameLoader_Impl4loadERKN3com3sun4star3uno8SequenceINS3_5beans13PropertyValueEEERKNS4_9ReferenceINS3_5frame6XFrameEEE + 10115
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -47  libfwklo.dylib                      0x000000010d679fde _ZN9framework7LoadEnv16impl_loadContentEv + 2654
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -48  libfwklo.dylib                      0x000000010d676aec _ZN9framework7LoadEnv5startEv + 124
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -49  libfwklo.dylib                      0x000000010d675120 _ZN9framework7LoadEnv12startLoadingERKN3rtl8OUStringERKN3com3sun4star3uno8SequenceINS7_5beans13PropertyValueEEERKNS8_9ReferenceINS7_5frame6XFrameEEES4_i15LoadEnvFeatures + 1296
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -50  libfwklo.dylib                      0x000000010d6747dc _ZN9framework7LoadEnv20loadComponentFromURLERKN3com3sun4star3uno9ReferenceINS3_5frame16XComponentLoaderEEERKNS5_INS4_17XComponentContextEEERKN3rtl8OUStringESI_iRKNS4_8SequenceINS3_5beans13PropertyValueEEE + 780
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -51  libfwklo.dylib                      0x000000010d6a365d _ZN9framework7Desktop20loadComponentFromURLERKN3rtl8OUStringES4_iRKN3com3sun4star3uno8SequenceINS7_5beans13PropertyValueEEE + 557
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -52  libfwklo.dylib                      0x000000010d6a3822 _ZThn120_N9framework7Desktop20loadComponentFromURLERKN3rtl8OUStringES4_iRKN3com3sun4star3uno8SequenceINS7_5beans13PropertyValueEEE + 18
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -53  libgcc3_uno.dylib                   0x0000000117272ab6 _ZN4gcc317callVirtualMethodEPvjS0_P33_typelib_TypeDescriptionReferencebPmjS3_Pd + 326
2021-11-03 10:11:29.543 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -54  libgcc3_uno.dylib                   0x0000000117272397 _ZL8cpp_callPN7bridges7cpp_uno6shared17UnoInterfaceProxyENS1_10VtableSlotEP33_typelib_TypeDescriptionReferenceiP24_typelib_MethodParameterPvPS9_PP8_uno_Any + 1399
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -55  libgcc3_uno.dylib                   0x0000000117271d48 unoInterfaceProxyDispatch + 728
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -56  libbinaryurplo.dylib                0x000000011754a29b _ZNK9binaryurp15IncomingRequest13execute_throwEPNS_9BinaryAnyEPNSt3__16vectorIS1_NS3_9allocatorIS1_EEEE + 1451
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -57  libbinaryurplo.dylib                0x0000000117549850 _ZNK9binaryurp15IncomingRequest7executeEv + 144
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -58  libbinaryurplo.dylib                0x000000011754f46f request + 15
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -59  libuno_cppu.dylib.3                 0x000000010d164f67 _ZN15cppu_threadpool8JobQueue5enterEPKvb + 231
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -60  libuno_cppu.dylib.3                 0x000000010d167b83 _ZN15cppu_threadpool14ORequestThread3runEv + 147
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -61  libuno_cppu.dylib.3                 0x000000010d167e8f threadFunc + 15
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -62  libuno_sal.dylib.3                  0x000000010ce44d0a _ZL21osl_thread_start_ImplPv + 122
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -63  libsystem_pthread.dylib             0x00007fff2043d8fc _pthread_start + 224
2021-11-03 10:11:29.544 [Thread-16] ERROR org.jodconverter.local.office.VerboseProcess.run:83 -64  libsystem_pthread.dylib             0x00007fff20439443 thread_start + 15
2021-11-03 10:11:29.546 [MessageDispatcher] INFO  org.jodconverter.local.office.OfficeConnection.disposing:221 -Disconnected from 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2021-11-03 10:11:29.547 [MessageDispatcher] WARN  org.jodconverter.local.office.LocalOfficeManagerPoolEntry.disconnected:104 -Connection lost unexpectedly; attempting restart
2021-11-03 10:11:29.547 [MessageDispatcher] INFO  org.jodconverter.local.office.LocalOfficeProcessManager.restartDueToLostConnection:254 -Restarting due to lost connection...
2021-11-03 10:11:29.548 [jodconverter-offprocmng-0] INFO  org.jodconverter.local.office.LocalOfficeProcessManager.ensureProcessExited:719 -Process exited with code 134
2021-11-03 10:11:29.550 [jodconverter-poolentry-1] ERROR org.jodconverter.local.task.LocalConversionTask.execute:131 -Local conversion failed.
com.sun.star.uno.RuntimeException: com.sun.star.lib.uno.environments.remote.JobQueue.removeJob - unexpected:java.lang.InterruptedException
	at com.sun.star.lib.uno.environments.remote.JobQueue.removeJob(JobQueue.java:222)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:330)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy228.loadComponentFromURL(Unknown Source)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:114)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:117)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-11-03 10:11:29.565 [jodconverter-offprocmng-0] INFO  org.jodconverter.local.office.OfficeDescriptor.fromExecutablePath:100 -soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2021-11-03 10:11:29.858 [jodconverter-offprocmng-0] INFO  org.jodconverter.local.office.OfficeDescriptor.fromHelpOutput:75 -soffice info (from help output): Product: LibreOffice - Version: 7.2.2.2 - useLongOptionNameGnuStyle: true
2021-11-03 10:11:29.958 [jodconverter-offprocmng-0] INFO  org.jodconverter.local.office.LocalOfficeProcessManager.startProcessAndConnect:395 -Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/var/folders/2x/bnmf63_j2kj5734tp_y9n9f40000gp/T/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'

**Comment by sbraconnier** [comment]
Sorry for the late anwser. Do you still have this issue?

Seems to be a doc and not a pptx conversion.

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
