### ISSUE TITLE
转pdf异常，Caused by: com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///D:/officedest/home/data/localpath/servicecenter/20210817/20210817094906679504091671043/Unit%201%20B%20Read%20and%20write基于深度学习的教学课件.pdf> failed: 0x11b(Error Area:Io Class:Abort Code:27)

### ISSUE THREAD

**Issue by jikuanyu** [sbraconnier/jodconverter#287]
jobconverter:
    `
    <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-local</artifactId>
            <version>4.4.2</version>
        </dependency>
`
libreoffice:
[LibreOffice_7.3.1_Win_x64.msi](https://mirrors.nju.edu.cn/tdf/libreoffice/stable/7.3.1/win/x86_64/LibreOffice_7.3.1_Win_x64.msi)

code:
```
public class OpenOfficeService implements ConvertToPdf {

    private LocalOfficeManager officeManager;

    public LocalOfficeManager getOfficeManager() {
        return officeManager;
    }

    @PostConstruct
    public void start() throws OfficeException {
        if (officeManager != null) {
            return;
        }
        int cpuNum = (int) (CommonUtil.CPU_NUM * 0.8);
        if (cpuNum < 1) {
            cpuNum = 1;
        }
        int startPort = 8101;
        String[] ports = new String[cpuNum];
        for (int i = 0; i < cpuNum; i++) {
            ports[i] = "P-"+startPort;
            startPort++;
        }

        //文档最长转换时长10m
        final long i = 1000L * 60 * 10;
        officeManager =
                LocalOfficeManager.builder().processTimeout(i)
                        .install()
                        .pipeNames(ports)
                        .officeHome("C:\\Program Files\\LibreOffice\\").build();
        officeManager.start();
    }

  

    @Override
    public boolean convert(String inputFilePath, String outFilePath) {
        try {
            JodConverter.convert(new File(inputFilePath)).to(new File(outFilePath)).execute();
            return true;
        } catch (OfficeException e) {
            e.printStackTrace();
            throw new RuntimeException(e.getMessage());
        }
    }

    @PreDestroy
    public void stop() {
        OfficeUtils.stopQuietly(officeManager);
    }

    @Override
    public boolean isValidate() {
        return false;
    }
}
```

error:
ERROR o.j.local.task.LocalConversionTask - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not store document: Unit 1 B Read and write基于深度学习的教学课件.pdf
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:186)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:119)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///D:/officedest/home/data/localpath/servicecenter/20210817/20210817094906679504091671043/Unit%201%20B%20Read%20and%20write基于深度学习的教学课件.pdf> failed: 0x11b(Error Area:Io Class:Abort Code:27)
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy160.storeToURL(Unknown Source)
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:180)
	... 7 common frames omitted
org.jodconverter.core.office.OfficeException: Could not store document: Unit 1 B Read and write基于深度学习的教学课件.pdf
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:186)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:119)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///D:/officedest/home/data/localpath/servicecenter/20210817/20210817094906679504091671043/Unit%201%20B%20Read%20and%20write基于深度学习的教学课件.pdf> failed: 0x11b(Error Area:Io Class:Abort Code:27)
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy160.storeToURL(Unknown Source)
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:180)
	... 7 more

期待回复，谢谢。

**Comment by gaoxingzaq** [comment]
是文件名 编码问题吧 无法保存特殊符号

**Comment by sbraconnier** [comment]
Do you still have this problem??

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
