### ISSUE TITLE
linux+docker+libreoffice，spring-boot + jodconverter，Could not start the office process.

### ISSUE THREAD

**Issue by LukuanWang** [sbraconnier/jodconverter#292]
On the windows environment, I downloaded a libreoffice and successfully used spring boot + jodconverter for file conversion.
However, I took libreoffice as the basic docker-image in Debian environment, deployed my project in this basic image, and reported an error during file conversion.

> [jodconverter-offprocmng-0] ERROR o.j.l.o.LocalOfficeProcessManager 217 - Could not start the office process.
org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager'
        at org.jodconverter.local.office.LocalOfficeProcessManager.startProcessAndConnect(LocalOfficeProcessManager.java:417)
        at org.jodconverter.local.office.LocalOfficeProcessManager.lambda$start$1(LocalOfficeProcessManager.java:215)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jodconverter.core.office.RetryTimeoutException: null
        at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:86)
        at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:54)
        at org.jodconverter.local.office.LocalOfficeProcessManager.startProcessAndConnect(LocalOfficeProcessManager.java:405)
        ... 4 common frames omitted

>  o.j.l.o.LocalOfficeProcessManager 293 - Restarting due to task timeout...
org.jodconverter.core.office.OfficeException: Task did not complete within timeout: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties=null, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
        at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:118)
        at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:217)
        at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:149)
        at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:62)

libreoffice‘s version is 6.1.5.2，jodconverter's version is 4.4.2

**Comment by LukuanWang** [comment]
> 
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2022-04-02 10:39:34.198  INFO 6 --- [           main] org.example.DemoApplication              : Starting DemoApplication v1.0.0 on 9f2bb7ab3c40 with PID 6 (/demo/my_demo-1.0.0.jar started by root in /                                         demo)
2022-04-02 10:39:34.236  INFO 6 --- [           main] org.example.DemoApplication              : No active profile set, falling back to default profiles: default
2022-04-02 10:39:44.806  INFO 6 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8099 (http)
2022-04-02 10:39:45.049  INFO 6 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-04-02 10:39:45.059  INFO 6 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2022-04-02 10:39:45.115  INFO 6 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments w                                         as not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
2022-04-02 10:39:45.489  INFO 6 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-04-02 10:39:45.499  INFO 6 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 10815 ms
2022-04-02 10:39:46.275  INFO 6 --- [er-offprocmng-0] o.j.local.office.OfficeDescriptor        : soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2022-04-02 10:39:46.773  INFO 6 --- [er-offprocmng-0] o.j.local.office.OfficeDescriptor        : soffice info (from help output): Product: LibreOffice - Version: 6.1.5.2 - useLongOptionNameGnuStyle: tr                                         ue
2022-04-02 10:39:46.795  INFO 6 --- [er-offprocmng-0] o.j.l.office.LocalOfficeProcessManager   : Starting process with --accept 'socket,host=0.0.0.0,port=2005,tcpNoDelay=1;urp;StarOffice.ServiceManager                                         ' and profileDir '/tmp/.jodconverter_socket_host-0.0.0.0_port-2005_tcpNoDelay-1'
2022-04-02 10:39:47.914  WARN 6 --- [er-offprocmng-0] o.j.l.o.StartProcessAndConnectRetryable  : Office process died with exit code 81; restarting it



2022-04-02 10:42:47.954  WARN 6 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.be                                         ans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoController': Unsatisfied dependency expressed through field 'converter'; nested exception is org.springframework.beans.fac                                         tory.UnsatisfiedDependencyException: Error creating bean with name 'localDocumentConverter' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]                                         : Unsatisfied dependency expressed through method 'localDocumentConverter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'local                                         OfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Invocation of init method failed; nested exception is org.jodconverter.core                                         .office.OfficeException: An error prevents us to start a process with --accept 'socket,host=0.0.0.0,port=2005,tcpNoDelay=1;urp;StarOffice.ServiceManager'
2022-04-02 10:42:47.979  INFO 6 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-04-02 10:42:48.089  INFO 6 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-02 10:42:48.125 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoController': Unsatisfied dependency expressed through field 'converter'; nested exception is org.spr                                         ingframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'localDocumentConverter' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAu                                         toConfiguration.class]: Unsatisfied dependency expressed through method 'localDocumentConverter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating                                          bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Invocation of init method failed; nested exception is                                          org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=0.0.0.0,port=2005,tcpNoDelay=1;urp;StarOffice.ServiceManager'
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.5.RELEASE.jar                                         !/:5.1.5.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.                                         5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.example.DemoApplication.main(DemoApplication.java:13) ~[classes!/:1.0.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[my_demo-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[my_demo-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[my_demo-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[my_demo-1.0.0.jar:1.0.0]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'localDocumentConverter' defined in class path resource [org/jodconverter/boot/autoconfigure/J                                         odConverterLocalAutoConfiguration.class]: Unsatisfied dependency expressed through method 'localDocumentConverter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationExcepti                                         on: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Invocation of init method failed; n                                         ested exception is org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=0.0.0.0,port=2005,tcpNoDelay=1;urp;StarOffice.ServiceManager'
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305) ~[spring-beans-5.1.5.RELEASE.jar!/:5.                                         1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE                                         ]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593) ~[spring-beans-5.1.5.RELEASE.jar                                         !/:5.1.5.RELEASE]
        ... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLo                                         calAutoConfiguration.class]: Invocation of init method failed; nested exception is org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=0.0.0                                         .0,port=2005,tcpNoDelay=1;urp;StarOffice.ServiceManager'
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        ... 40 common frames omitted
Caused by: org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=0.0.0.0,port=2005,tcpNoDelay=1;urp;StarOffice.ServiceManager'
        at org.jodconverter.local.office.LocalOfficeProcessManager.startProcessAndConnect(LocalOfficeProcessManager.java:417) ~[jodconverter-local-4.4.2.jar!/:4.4.2]
        at org.jodconverter.local.office.LocalOfficeProcessManager.lambda$start$0(LocalOfficeProcessManager.java:188) ~[jodconverter-local-4.4.2.jar!/:4.4.2]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.jodconverter.core.office.RetryTimeoutException: null
        at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:86) ~[jodconverter-core-4.4.2.jar!/:4.4.2]
        at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:54) ~[jodconverter-core-4.4.2.jar!/:4.4.2]
        at org.jodconverter.local.office.LocalOfficeProcessManager.startProcessAndConnect(LocalOfficeProcessManager.java:405) ~[jodconverter-local-4.4.2.jar!/:4.4.2]
        ... 5 common frames omitted


this is my demo which i want to use jodconverter + libreoffice(docker) + springboot ,but i got RetryTimeoutException;
i don't know where was the error.


> public class DemoController {

    @Autowired
    private DocumentConverter converter;

    @PostMapping("/docToPdf")
    @ApiOperation("DOCX转PDF")
    @ApiImplicitParam(name = "multipartFile",value = "multipartFile",required = true,paramType = "String")
    public AjaxResult docxToPdf(MultipartFile multipartFile, HttpServletResponse response) throws IOException {
        File targetFile  = new File(System.getProperty("java.io.tmpdir"),
                Objects.requireNonNull(multipartFile.getOriginalFilename()).split("\\.")[0] + ".pdf");
        try {
            converter.convert(multipartFile.getInputStream()).to(targetFile).execute();
            return AjaxResult.success();
        } catch (OfficeException e) {
            e.printStackTrace();
            return AjaxResult.error();
        }
    }
}

>          4.4.2
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-spring-boot-starter</artifactId>
            <version>${jodconverter.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-local</artifactId>
            <version>${jodconverter.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-remote</artifactId>
            <version>${jodconverter.version}</version>
        </dependency>


> 
![image](https://user-images.githubusercontent.com/70249991/161379854-7a9a9899-0d09-4920-8d3a-add6e4db2502.png)


thank u very much!!!

**Comment by LukuanWang** [comment]
This problem has been solved. I replaced the libreoffice image

Previously, it was installed manually through DEB file. This time, I used the image of version 5.2 on GitHub

thank u very much!!!

**Comment by sbraconnier** [comment]
Glad to hear that!! Thanks!

**Comment by consyxy** [comment]
@LukuanWang hey I'm trying to do similar things as you, I tried to install libreoffice in my docker file by "apt-get", and try to use in a java program, where did you find that github image?
