### ISSUE TITLE
ServiceManager started but its pid could not be found. happened Occasionally

### ISSUE THREAD

**Issue by darrenXJ** [sbraconnier/jodconverter#294]
2022-04-24 10:41:03,528 [localhost-startStop-1] [INFO ] org.jodconverter.office.OfficeProcessManager:293 - Submitting task 'Start' and waiting...
2022-04-24 10:41:03,534 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:41:03,579 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:141 - Command Output: 
 7185 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2022-04-24 10:41:03,579 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:176 - Checking if process line matches the process line regex
Process line:  7185 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2022-04-24 10:41:03,579 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:182 - Line matches!
pid: 7185; Command line: /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2022-04-24 10:41:03,579 [OfficeProcessThread-0] [DEBUG] org.jodconverter.process.AbstractProcessManager:190 - Command line matches! Returning pid: 7185
2022-04-24 10:41:03,579 [OfficeProcessThread-0] [WARN ] org.jodconverter.office.OfficeProcess:92 - A process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' is already running; pid 7185
2022-04-24 10:41:04,581 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:41:04,602 [OfficeProcessThread-0] [WARN ] org.jodconverter.office.OfficeProcess:244 - Profile dir '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1' already exists; deleting
2022-04-24 10:41:04,602 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeProcess:120 - Deleting instance profile directory '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
2022-04-24 10:41:04,624 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeProcess:337 - Starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
2022-04-24 10:41:04,626 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:41:04,642 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:141 - Command Output: 
15252 [soffice.bin]
2022-04-24 10:41:04,642 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:176 - Checking if process line matches the process line regex
Process line: 15252 [soffice.bin]
2022-04-24 10:41:04,642 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:182 - Line matches!
pid: 15252; Command line: [soffice.bin]
Checking if this command line matches the office command line regex
2022-04-24 10:41:04,643 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeProcess:344 - Started process; pid = -2
2022-04-24 10:41:04,677 [localhost-startStop-1] [DEBUG] org.jodconverter.office.OfficeProcessManager:302 - ExecutionException catched in submitAndWait
java.util.concurrent.ExecutionException: org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.	
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_192]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_192]
	at org.jodconverter.office.OfficeProcessManager.submitAndWait(OfficeProcessManager.java:298) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.startAndWait(OfficeProcessManager.java:253) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManagerPoolEntry.doStart(OfficeProcessManagerPoolEntry.java:168) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractOfficeManagerPoolEntry.start(AbstractOfficeManagerPoolEntry.java:144) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractOfficeManagerPool.doStart(AbstractOfficeManagerPool.java:214) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractOfficeManagerPool.start(AbstractOfficeManagerPool.java:134) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.LocalOfficeManager.start(LocalOfficeManager.java:36) [jodconverter-local-4.1.0.jar:4.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at 
2022-04-24 10:57:36,358 [localhost-startStop-1] [INFO ] org.jodconverter.office.OfficeProcessManager:293 - Submitting task 'Start' and waiting...
2022-04-24 10:57:36,361 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:57:36,383 [OfficeProcessThread-0] [WARN ] org.jodconverter.office.OfficeProcess:244 - Profile dir '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1' already exists; deleting
2022-04-24 10:57:36,383 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeProcess:120 - Deleting instance profile directory '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
2022-04-24 10:57:36,402 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeProcess:337 - Starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
2022-04-24 10:57:36,404 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:57:36,426 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:141 - Command Output: 
16354 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2022-04-24 10:57:36,426 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:176 - Checking if process line matches the process line regex
Process line: 16354 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2022-04-24 10:57:36,426 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:182 - Line matches!
pid: 16354; Command line: /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2022-04-24 10:57:36,426 [OfficeProcessThread-0] [DEBUG] org.jodconverter.process.AbstractProcessManager:190 - Command line matches! Returning pid: 16354
2022-04-24 10:57:36,427 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeProcess:344 - Started process; pid = 16354
2022-04-24 10:57:36,431 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:36,476 [OfficeProcessThread-0] [TRACE] org.jodconverter.office.OfficeProcess:178 - IllegalThreadStateException catch in getExitCode
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[na:1.8.0_192]
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:176) ~[jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:72) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255) [jodconverter-local-4.1.0.jar:4.1.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
2022-04-24 10:57:36,726 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:36,728 [OfficeProcessThread-0] [TRACE] org.jodconverter.office.OfficeProcess:178 - IllegalThreadStateException catch in getExitCode
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[na:1.8.0_192]
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:176) ~[jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:72) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255) [jodconverter-local-4.1.0.jar:4.1.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
2022-04-24 10:57:36,978 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:36,980 [OfficeProcessThread-0] [WARN ] org.jodconverter.office.ConnectRetryable:82 - Office process died with exit code 81; restarting it
2022-04-24 10:57:36,980 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:57:36,998 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeProcess:337 - Starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
2022-04-24 10:57:37,000 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:161 - Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2022-04-24 10:57:37,017 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:141 - Command Output: 
16373 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2022-04-24 10:57:37,018 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:176 - Checking if process line matches the process line regex
Process line: 16373 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2022-04-24 10:57:37,018 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:182 - Line matches!
pid: 16373; Command line: /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2022-04-24 10:57:37,018 [OfficeProcessThread-0] [DEBUG] org.jodconverter.process.AbstractProcessManager:190 - Command line matches! Returning pid: 16373
2022-04-24 10:57:37,018 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeProcess:344 - Started process; pid = 16373
2022-04-24 10:57:37,269 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:37,270 [OfficeProcessThread-0] [TRACE] org.jodconverter.office.OfficeProcess:178 - IllegalThreadStateException catch in getExitCode
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[na:1.8.0_192]
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:176) ~[jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:72) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255) [jodconverter-local-4.1.0.jar:4.1.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
2022-04-24 10:57:37,521 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:37,523 [OfficeProcessThread-0] [TRACE] org.jodconverter.office.OfficeProcess:178 - IllegalThreadStateException catch in getExitCode
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[na:1.8.0_192]
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:176) ~[jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:72) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255) [jodconverter-local-4.1.0.jar:4.1.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
2022-04-24 10:57:37,773 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:37,775 [OfficeProcessThread-0] [TRACE] org.jodconverter.office.OfficeProcess:178 - IllegalThreadStateException catch in getExitCode
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[na:1.8.0_192]
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:176) ~[jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:72) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57) [jodconverter-core-4.1.0.jar:4.1.0]
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260) [jodconverter-local-4.1.0.jar:4.1.0]
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255) [jodconverter-local-4.1.0.jar:4.1.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
2022-04-24 10:57:38,025 [OfficeProcessThread-0] [DEBUG] org.jodconverter.office.OfficeConnection:90 - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:38,100 [OfficeProcessThread-0] [INFO ] org.jodconverter.office.OfficeConnection:161 - Connected: 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2022-04-24 10:57:38,102 [localhost-startStop-1] [DEBUG] org.jodconverter.office.OfficeProcessManager:299 - Task 'Start' executed successfully

==================================================================
 10:41:04,642 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:141 - Command Output: 
15252 [soffice.bin]   

10:57:36,426 [OfficeProcessThread-0] [TRACE] org.jodconverter.process.AbstractProcessManager:141 - Command Output: 
16354 /iyunwen/server/libreoffice7.3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///iyunwen/server/tomcat_admin/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport

The above is the difference, it bothers me.

**Comment by sbraconnier** [comment]
Are you still having this problem ??? I didn't find in your log where the pid was not found. Everything seems to work as expected...

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
