### ISSUE TITLE
java.lang.StackOverflowError While converting docx to pdf, if document is more then 9 MB 

### ISSUE THREAD

**Issue by vinaysharma1987** [sbraconnier/jodconverter#299]
While we are converting from .docx to pdf we are getting following exception
only when file size is more then 9MB

org.jodconverter.core.office.OfficeException: Task did not complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties=null, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:104)
at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:217)
at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:149)
at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:62)

Caused by: java.lang.StackOverflowError

at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)

**Comment by sbraconnier** [comment]
Could you provide a sample document I could work with to reproduce the issue ?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
