### ISSUE TITLE
jodconverter not able to open Libre office connection in Linux environment ( org.artofsolving.jodconverter.office.OfficeException: could not establish connection) 

### ISSUE THREAD

**Issue by chaitanyayaga** [sbraconnier/jodconverter#308]
Hi there,
we are getting org.artofsolving.jodconverter.office.OfficeException: could not establish connection Exception when trying the start Libre office using JodConverter, Please help. It is not even giving any exit codes

2022.09.08 10.21.05.150 ALL   correspondence [default task-129]: Inside convertToPDF: FileExt: vnd.openxmlformats-officedocument.wordprocessingml.document
2022.09.08 10.21.05.151 ALL   correspondence [default task-129]: Inside Doc Docx Conversion
2022.09.08 10.21.05.151 ERROR correspondence [default task-129]: CoPdfUtility pdf conversion start time 1662646865151
2022.09.08 10.21.05.151 ERROR correspondence [default task-129]: Inside Doc Docx Conversion
2022.09.08 10.21.05.151 ERROR correspondence [default task-129]: Office Location is/apps/iedss/LibreOffice5_DEV_4_Server
2022.09.08 10.21.05.151 ERROR correspondence [default task-129]: Office Port is2002
2022.09.08 10.21.05.252 ALL   correspondence [default task-129]: Inside convertToPDF: Exception while starting the office at location /apps/iedss/LibreOffice5_DEV_4_Serverport 2002 
org.artofsolving.jodconverter.office.OfficeException: failed to start and connect
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess.startAndWait(ManagedOfficeProcess.java:64) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.PooledOfficeManager.start(PooledOfficeManager.java:101) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.ProcessPoolOfficeManager.start(ProcessPoolOfficeManager.java:62) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at ng.wp.common.util.CoPdfUtility.convertToPDF(CoPdfUtility.java:593) ~[common.jar:?]
	at ng.wp.dm.doc.services.ejb.DPSDocManagementSessionEJBBean.viewDocumentFromDPS(DPSDocManagementSessionEJBBean.java:909) ~[DM.jar:?]
	at ng.wp.dm.doc.services.ejb.DPSDocManagementSessionEJBBean.viewDMDOC(DPSDocManagementSessionEJBBean.java:856) ~[DM.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509) ~[?:?]
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79) ~[?:?]
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89) ~[?:?]
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102) ~[?:?]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40) ~[jboss-invocation-1.6.0.Final-redhat-00001.jar!/:1.6.0.Final-redhat-00001]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53) ~[?:?]
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:254) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:390) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:160) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509) ~[?:?]
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72) ~[weld-ejb-3.1.6.Final-redhat-00001.jar!/:3.1.6.Final-redhat-00001]
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89) ~[wildfly-weld-common-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438) ~[?:?]
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:633) ~[wildfly-elytron-security-manager-1.15.3.Final-redhat-00001.jar!/:1.15.3.Final-redhat-00001]
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53) ~[?:?]
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198) ~[?:?]
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:191) ~[?:?]
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:81) ~[?:?]
	at ng.wp.dm.doc.services.ejb.DPSDocManagementSessionEJBBean$$$view237.viewDMDOC(Unknown Source) ~[DM.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at ng.wp.framework.presentation.controller.ServiceController.processPage(ServiceController.java:1560) ~[FW.jar:?]
	at ng.wp.framework.presentation.controller.ServiceController.processInformation(ServiceController.java:559) ~[FW.jar:?]
	at ng.wp.framework.presentation.delegate.ControllerSessionBean.processRequest(ControllerSessionBean.java:126) ~[FW.jar:?]
	at sun.reflect.GeneratedMethodAccessor561.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509) ~[?:?]
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79) ~[?:?]
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89) ~[?:?]
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102) ~[?:?]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40) ~[jboss-invocation-1.6.0.Final-redhat-00001.jar!/:1.6.0.Final-redhat-00001]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53) ~[?:?]
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52) ~[wildfly-ee-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:232) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.notSupported(CMTTxInterceptor.java:373) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:149) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509) ~[?:?]
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81) ~[weld-ejb-3.1.6.Final-redhat-00001.jar!/:3.1.6.Final-redhat-00001]
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89) ~[wildfly-weld-common-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67) ~[wildfly-ejb3-7.4.0.GA-redhat-00005.jar!/:7.4.0.GA-redhat-00005]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438) ~[?:?]
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:633) ~[wildfly-elytron-security-manager-1.15.3.Final-redhat-00001.jar!/:1.15.3.Final-redhat-00001]
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57) ~[?:?]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[?:?]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53) ~[?:?]
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198) ~[?:?]
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:191) ~[?:?]
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:81) ~[?:?]
	at ng.wp.framework.presentation.delegate.ControllerSessionBean$$$view287.processRequest(Unknown Source) ~[FW.jar:?]
	at ng.wp.framework.presentation.controller.Controller.delegate(Controller.java:152) ~[FW.jar:?]
	at ng.wp.framework.presentation.controller.Controller.execute(Controller.java:121) ~[FW.jar:?]
	at ng.wp.framework.presentation.controller.GenericControllerServlet.service(GenericControllerServlet.java:1730) ~[classes:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jboss-servlet-api_4.0_spec-2.0.0.Final-redhat-00001.jar!/:2.0.0.Final-redhat-00001]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.5.Final-redhat-00001.jar!/:2.2.5.Final-redhat-00001]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[?:?]
	at ng.wp.framework.presentation.controller.MDCFilter.doFilter(MDCFilter.java:75) ~[classes:?]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[?:?]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[?:?]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[?:?]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[?:?]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[?:?]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[?:?]
	at org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68) ~[?:?]
	at org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103) ~[wildfly-elytron-auth-server-1.15.3.Final-redhat-00001.jar!/:1.15.3.Final-redhat-00001]
	at org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161) ~[wildfly-elytron-auth-server-1.15.3.Final-redhat-00001.jar!/:1.15.3.Final-redhat-00001]
	at org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73) ~[wildfly-elytron-auth-server-1.15.3.Final-redhat-00001.jar!/:1.15.3.Final-redhat-00001]
	at org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67) ~[?:?]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[?:?]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[?:?]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[?:?]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[?:?]
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) ~[?:?]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[?:?]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[?:?]
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) ~[?:?]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[?:?]
	at org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38) ~[?:?]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[?:?]
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) ~[?:?]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[?:?]
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) ~[?:?]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[?:?]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) ~[?:?]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[?:?]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) ~[?:?]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) ~[?:?]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[?:?]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841) ~[?:?]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[?:?]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990) ~[?:?]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) ~[?:?]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) ~[?:?]
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: java.util.concurrent.ExecutionException: org.artofsolving.jodconverter.office.OfficeException: could not establish connection
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_321]
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess.startAndWait(ManagedOfficeProcess.java:62) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	... 187 more
Caused by: org.artofsolving.jodconverter.office.OfficeException: could not establish connection
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:142) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess.access$000(ManagedOfficeProcess.java:31) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess$1.run(ManagedOfficeProcess.java:58) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_321]
	... 1 more
Caused by: java.lang.IllegalStateException: process with acceptString 'socket,host=127.0.0.1,port=2002' started but its pid could not be found
	at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:97) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:61) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:119) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess.access$000(ManagedOfficeProcess.java:31) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at org.artofsolving.jodconverter.office.ManagedOfficeProcess$1.run(ManagedOfficeProcess.java:58) ~[jodconverter-core-3.0-beta-4-jahia4.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_321]
	... 1 more

**Comment by chaitanyayaga** [comment]
Thanks for the update Simon, we will upgrade the jodconverter

**Comment by sbraconnier** [comment]
I'll close this one for now. Feel free to reopen it if it still does work after your upgrade.
