### ISSUE TITLE
org.jodconverter.core.office.OfficeException: Could not open document: tempfile_0 when using OpenOffice

### ISSUE THREAD

**Issue by carcuevas** [sbraconnier/jodconverter#314]
Hi ,

when trying to do the conversion using `jodconverter-sample-spring-boot` and OpenOffice (when using LibreOffice is working) I am getting this error, when trying to convert from ODT to PDF:

```
2022-11-09 20:37:16 DEBUG o.j.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-11-09 20:37:17 INFO  o.j.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-11-09 20:37:17 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution succeeded on attempt #6
2022-11-09 20:37:17 INFO  o.j.l.o.LocalOfficeProcessManager - Started process; pid: 25365


2022-11-09 20:38:13 DEBUG o.j.c.o.AbstractOfficeManagerPool - Acquiring an office manager from the pool...
2022-11-09 20:38:13 DEBUG o.j.c.o.AbstractOfficeManagerPool - Office manager acquired successfully from the pool.
2022-11-09 20:38:13 DEBUG o.j.c.o.AbstractOfficeManagerPoolEntry - Waiting 120000 ms for task to complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
2022-11-09 20:38:13 DEBUG o.j.l.o.LocalOfficeManagerPoolEntry - Executing task: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
2022-11-09 20:38:13 INFO  o.j.local.task.LocalConversionTask - Executing local conversion task [? -> pdf]...
2022-11-09 20:38:13 ERROR o.j.local.task.LocalConversionTask - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not open document: tempfile_0
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:201)
        at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:119)
        at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
        at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
        at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
        at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
        at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
        at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
        at jdk.proxy2/jdk.proxy2.$Proxy65.loadComponentFromURL(Unknown Source)
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:187)
        ... 7 common frames omitted
2022-11-09 20:38:13 DEBUG o.j.c.o.AbstractOfficeManagerPool - Returning office manager to the pool...

```

Of course the file is **not** called `tempfile_0` I guess is whenever I POST the file to the service it's changing the name or something like this... It is strange that it's happening....

Also the build.gradle for the jodconverter-sample-spring-boot is:

```
plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'war'
    id 'org.springframework.boot' version '2.7.3'
}

group = 'org.jodconverter'
description = 'JODConverter - Sample Spring Boot Web Application'

ext {
    commonsIoVersion = '2.11.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":jodconverter-local-oo")
    implementation project(":jodconverter-spring-boot-starter")

    implementation "commons-io:commons-io:$commonsIoVersion"

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-thymeleaf"
    implementation "org.springframework.boot:spring-boot-devtools"
}

```

The soffice is running as:

```
/opt/openoffice4/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -headless -invisible -nocrashreport -nodefault -nofirststartwizard -nolockcheck -nologo -norestore -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1

```
not sure if I should define some path or something in the gradle configs... or what should I change.... 

thanks :)

**Comment by carcuevas** [comment]
The OpenOffice packages installed are: 

```
ii  openoffice                       4.1.13-1                                  amd64        Brand module for OpenOffice 4.1.13
ii  openoffice-core01                4.1.13-1                                  amd64        Core module for Apache OpenOffice 4.1.13
ii  openoffice-core02                4.1.13-1                                  amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core03                4.1.13-1                                  amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core04                4.1.13-1                                  amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core05                4.1.13-1                                  amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core06                4.1.13-1                                  amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core07                4.1.13-1                                  amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-debian-menus          4.1.13-9810                               all          OpenOffice desktop integration
ii  openoffice-en-us                 4.1.13-1                                  amd64        Language module for Apache OpenOffice 4.1.13, language en_US
ii  openoffice-en-us-res             4.1.13-1                                  amd64        Language resource module for Apache OpenOffice 4.1.13, language en_US
ii  openoffice-images                4.1.13-1                                  amd64        Images module for Apache OpenOffice 4.1.13
ii  openoffice-ure                   4.1.13-1                                  amd64        UNO Runtime Environment for OpenOffice 4.1.13
ii  openoffice-writer                4.1.13-1                                  amd64        Writer module for Apache OpenOffice 4.1.13
```

**Comment by sbraconnier** [comment]
Sorry for the delay. I'm quite busy these days...

I just tested successfully the odt to pdf conversion using the sample-spring-boot module.

I'm on Windows, using LO.

Is it possible for you to try the same thing with LibreOffice instead of OpenOffice and see if it works?

**Comment by carcuevas** [comment]
Hi @sbraconnier , there is no problem the end of the year is always busy :) in fact thanks for dedicating a bit of your time to this ... 

With LibreOffice it works, there is no problem, the main problem is when using OpenOffice, I am not sure, but I thought that maybe in OpenOffice is expecting some different parameter when when executing the `soffice` command?  or maybe something else... ? 

The system I using is a Debian 11.5 machine..

**Comment by sbraconnier** [comment]
@carcuevas I just tried the same sample as you on Windows and it worked as expected. I'm also using 4.1.13, so it's probably more related to the os environment.

If I upload a snapshot with a bit more verbosity (full file path instead of just the name) could you test it?

**Comment by carcuevas** [comment]
Hi @sbraconnier  uhmm interesting that it is working :) well I have told you  that I was using Debian 11, well I did a mistake I used Ubuntu 20.04, so I am installing now a debian 11 vm and I will try it once more sorry for that... 

But in any case I can happily  use any version you want to try so we can have more verbosity... thanks

**Comment by sbraconnier** [comment]
I made a small change in the `LocalConversionTask` that should display the full path of the files involved in the conversion (please set your log level to TRACE).

**Comment by carcuevas** [comment]
I updated the code, and recompile the `jodconverter-samples/jodconverter-sample-spring-boot` just sorry that I could not set up logs to TRACE level, I checked here https://github.com/sbraconnier/jodconverter/wiki/Configuration  but couldn't find it...   Sorry I couldn't find it...  unless I need to run the `java -jar jodconverter-samples/jodconverter-sample-spring-boot/build/libs/jodconverter-sample-spring-boot-4.4.5-SNAPSHOT.war` differently .... 

Anyways I had the same result, and the logs I had (without the TRACE level are: ) 



```
2022-12-20 10:08:33 INFO  o.j.s.s.SpringBootWebApplication - Starting SpringBootWebApplication using Java 17.0.4 with PID 37111 (/dist/jodconverter-gui.war started by root in /dist)
2022-12-20 10:08:33 DEBUG o.j.s.s.SpringBootWebApplication - Running with Spring Boot v2.7.6, Spring v5.3.24
2022-12-20 10:08:33 INFO  o.j.s.s.SpringBootWebApplication - No active profile set, falling back to 1 default profile: "default"
2022-12-20 10:08:36 DEBUG o.j.local.office.LocalOfficeUtils - Default office home set to /opt/openoffice4
2022-12-20 10:08:36 DEBUG o.j.c.o.AbstractOfficeManagerPool - Returning office manager to the pool...
2022-12-20 10:08:36 INFO  o.j.local.office.OfficeDescriptor - soffice info (from exec path): Product: OpenOffice - Version: ??? - useLongOptionNameGnuStyle: false
2022-12-20 10:08:36 DEBUG o.j.local.office.OfficeDescriptor - Building org.jodconverter.local.office.OfficeDescriptor from help output lines
2022-12-20 10:08:36 INFO  o.j.local.office.OfficeDescriptor - soffice info (from help output): Product: ??? - Version: ??? - useLongOptionNameGnuStyle: false
2022-12-20 10:08:36 DEBUG o.j.l.process.AbstractProcessManager - No matching command line found! Returning pid: NOT_FOUND
2022-12-20 10:08:36 DEBUG o.j.l.o.LocalOfficeProcessManager - Checking existing process done; no process running with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager'
2022-12-20 10:08:36 WARN  o.j.l.o.LocalOfficeProcessManager - Profile dir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1' already exists; deleting
2022-12-20 10:08:36 DEBUG o.j.core.office.OfficeUtils - Deleting '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2022-12-20 10:08:36 DEBUG o.j.c.o.OfficeUtils$DeleteFileRetryable - Execution attempt #1
2022-12-20 10:08:36 DEBUG o.j.c.o.OfficeUtils$DeleteFileRetryable - Execution succeeded on attempt #1
2022-12-20 10:08:36 DEBUG o.j.l.o.LocalOfficeProcessManager - ProcessBuilder command: /opt/openoffice4/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -headless -invisible -nocrashreport
-nodefault -nofirststartwizard -nolockcheck -nologo -norestore -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1
2022-12-20 10:08:36 DEBUG o.j.l.o.LocalOfficeProcessManager - OFFICE HOME: /opt/openoffice4
2022-12-20 10:08:36 INFO  o.j.l.o.LocalOfficeProcessManager - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNo
Delay-1'
2022-12-20 10:08:36 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #1
2022-12-20 10:08:36 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Trying to find pid, attempt #1
2022-12-20 10:08:36 DEBUG o.j.l.process.AbstractProcessManager - Command line matches! Returning pid: 37150
2022-12-20 10:08:36 DEBUG o.j.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-20 10:08:36 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #1 failed, retrying after sleep of 250 ms
2022-12-20 10:08:37 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #2
2022-12-20 10:08:37 DEBUG o.j.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-20 10:08:37 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #2 failed, retrying after sleep of 250 ms
2022-12-20 10:08:37 INFO  o.j.s.s.SpringBootWebApplication - Started SpringBootWebApplication in 4.394 seconds (JVM running for 6.111)
2022-12-20 10:08:37 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #3
2022-12-20 10:08:37 DEBUG o.j.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-20 10:08:37 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #3 failed, retrying after sleep of 250 ms
2022-12-20 10:08:37 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution attempt #4
2022-12-20 10:08:37 DEBUG o.j.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-20 10:08:37 INFO  o.j.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-20 10:08:37 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution succeeded on attempt #4
2022-12-20 10:08:37 INFO  o.j.l.o.LocalOfficeProcessManager - Started process; pid: 37150
2022-12-20 10:08:57 DEBUG o.j.c.o.AbstractOfficeManagerPool - Acquiring an office manager from the pool...
2022-12-20 10:08:57 DEBUG o.j.c.o.AbstractOfficeManagerPool - Office manager acquired successfully from the pool.
2022-12-20 10:08:57 DEBUG o.j.c.o.AbstractOfficeManagerPoolEntry - Waiting 120000 ms for task to complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, Upda
teDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
2022-12-20 10:08:57 DEBUG o.j.l.o.LocalOfficeManagerPoolEntry - Executing task: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=Target
DocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
2022-12-20 10:08:57 INFO  o.j.local.task.LocalConversionTask - Executing local conversion task [? -> pdf]...
2022-12-20 10:08:57 ERROR o.j.local.task.LocalConversionTask - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not open document: tempfile_0
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:199)
        at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:123)
        at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
        at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
        at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
        at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
```

**Comment by sbraconnier** [comment]
In order to activate the TRACE logging level, you have to update the `jodconverter-samples/jodconverter-sample-spring-boot/src/main/java/resources/logback.xml`

Change the level of the `org.jodconverter` logger from debug to trace.

**Comment by carcuevas** [comment]
Alright thanks, I Pulled the last version did the change and here down the logs... 


```
2022-12-21 10:08:55 DEBUG o.j.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-21 10:08:55 TRACE o.j.local.office.OfficeConnection - Connector created successfully, trying to connect...
2022-12-21 10:08:55 TRACE o.j.local.office.OfficeConnection - Connection done successfully, creating bridge...
2022-12-21 10:08:55 TRACE o.j.local.office.OfficeConnection - Bridge created successfully, initializing...
2022-12-21 10:08:55 INFO  o.j.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2022-12-21 10:08:55 TRACE o.j.l.o.StartProcessAndConnectRetryable - An attempt to connect to an office process succeeded
2022-12-21 10:08:55 DEBUG o.j.l.o.StartProcessAndConnectRetryable - Execution succeeded on attempt #4
2022-12-21 10:08:55 INFO  o.j.l.o.LocalOfficeProcessManager - Started process; pid: 1063
2022-12-21 10:09:21 DEBUG o.j.c.o.AbstractOfficeManagerPool - Acquiring an office manager from the pool...
2022-12-21 10:09:21 DEBUG o.j.c.o.AbstractOfficeManagerPool - Office manager acquired successfully from the pool.
2022-12-21 10:09:21 DEBUG o.j.c.o.AbstractOfficeManagerPoolEntry - Waiting 120000 ms for task to complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null, useStreamAdapters=false}
2022-12-21 10:09:21 DEBUG o.j.l.o.LocalOfficeManagerPoolEntry - Executing task: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null, useStreamAdapters=false}
2022-12-21 10:09:21 INFO  o.j.local.task.LocalConversionTask - Executing local conversion task [? -> pdf]...
2022-12-21 10:09:21 TRACE o.j.local.task.LocalConversionTask - Local conversion source file: /tmp/.jodconverter_c1ffc4cd-65a2-4ee2-9734-65b21fd1b285/tempfile_0
2022-12-21 10:09:21 TRACE o.j.local.task.LocalConversionTask - Local conversion target file: /tmp/.jodconverter_c1ffc4cd-65a2-4ee2-9734-65b21fd1b285/tempfile_1.pdf
2022-12-21 10:09:21 ERROR o.j.local.task.LocalConversionTask - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not open document: tempfile_0
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:218)
        at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:128)
        at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
        at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
        at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
        at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
        at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
        at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
        at jdk.proxy2/jdk.proxy2.$Proxy65.loadComponentFromURL(Unknown Source)
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocumentFromURL(AbstractLocalOfficeTask.java:239)
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:203)
        ... 7 common frames omitted
2022-12-21 10:09:21 DEBUG o.j.c.o.AbstractOfficeManagerPool - Returning office manager to the pool...
```

**Comment by carcuevas** [comment]
Ohh my!! Interesting that I had the same amount of `DEB` packages from the OpenOffice installed as in the "ancient" version of JODConverter ( I guess it was the 2.2.2) ... but now I installed everything and it seems to do the trick... 

@sbraconnier  I will try to identify the bare minimum amount of packages needed to make it work.... I can write it here later...  Sorry for this and thanks

**Comment by sbraconnier** [comment]
Don't be sorry :smile: !! Very happy to hear that it works now!

**Comment by carcuevas** [comment]
Thanks once more :) Here I write the bare minimum amount of packages needed for making it work from DEBIAN based OS:

```
dpkg -l |grep openoffice
ii  openoffice                           4.1.13-1                       amd64        Brand module for OpenOffice 4.1.13
ii  openoffice-calc                      4.1.13-1                       amd64        Calc module for Apache OpenOffice 4.1.13
ii  openoffice-core01                    4.1.13-1                       amd64        Core module for Apache OpenOffice 4.1.13
ii  openoffice-core02                    4.1.13-1                       amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core03                    4.1.13-1                       amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core04                    4.1.13-1                       amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core05                    4.1.13-1                       amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core06                    4.1.13-1                       amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-core07                    4.1.13-1                       amd64        Office core module for Apache OpenOffice 4.1.13
ii  openoffice-en-us                     4.1.13-1                       amd64        Language module for Apache OpenOffice 4.1.13, language en_US
ii  openoffice-en-us-res                 4.1.13-1                       amd64        Language resource module for Apache OpenOffice 4.1.13, language en_US
ii  openoffice-images                    4.1.13-1                       amd64        Images module for Apache OpenOffice 4.1.13
ii  openoffice-impress                   4.1.13-1                       amd64        Impress module for Apache OpenOffice 4.1.13
ii  openoffice-ure                       4.1.13-1                       amd64        UNO Runtime Environment for OpenOffice 4.1.13
ii  openoffice-writer                    4.1.13-1                       amd64        Writer module for Apache OpenOffice 4.1.13

```

Or once downloaded the OpenOffice DEB packages from here: https://sourceforge.net/projects/openofficeorg.mirror/files/4.1.13/binaries/en-US/Apache_OpenOffice_4.1.13_Linux_x86-64_install-deb_en-US.tar.gz/download  

```
dpkg -i openoffice-ure_*.deb openoffice-core*.deb  openoffice-writer_*.deb  openoffice-images_*.deb openoffice-calc_4*.deb openoffice-impress_4*.deb openoffice_4*_amd64.deb openoffice-en-us-res_4*.deb openoffice-en-us_4*_amd64.deb
```

Maybe somebody will find it useful next time ;-)

**Comment by sbraconnier** [comment]
I'll keep that one opened until I find where it should be documented! Good work!

**Comment by carcuevas** [comment]
perfect :) thanks very much
