### ISSUE TITLE
With 4.4.3+ i get an exception missing classes for the DefaultDocumentFormatRegistry

### ISSUE THREAD

**Issue by EugenMayer** [sbraconnier/jodconverter#317]
I'am currently updating https://github.com/EugenMayer/officeconverter to the newest jodconvert version.

Coming from 4.3.0 i can upgrade to 4.4.2 without issues, 4.4.3+ though throw me an error on the integration test

https://github.com/EugenMayer/officeconverter/blob/main/src/test/java/de/kontextwork/converter/web/ConversionControllerTest.java#L39

```
  org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jodconverter.core.document.DefaultDocumentFormatRegistry
      at app//de.kontextwork.converter.web.ConversionControllerTest.convertDotxWorks(ConversionControllerTest.java:75)
```

Anything unexpected changed with the Document Format Registry.

I checked the release notes https://github.com/sbraconnier/jodconverter/releases/tag/v4.4.3 and https://github.com/sbraconnier/jodconverter/releases/tag/v4.4.4 but did not find anything directly related.

Greatful for any help!

**Comment by EugenMayer** [comment]
It seems like also the plain recent builds are failing. E.g.

When starting the rest-variant it failes with:

```
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.22.jar!/:5.3.22]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.22.jar!/:5.3.22]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.22.jar!/:5.3.22]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
```

Which seems very much related. So i guess the same issue should current affect the `jodconverter-sample-rest` which i build in that repository. I guess it would be a good idea,  moving forward, to add a Application start smoke test to `https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest/src/main`

**Comment by EugenMayer** [comment]
Confirmed, using your current master and starting jodconverter-sample-rest i see

```
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.22.ja
```
