### ISSUE TITLE
How to configure the macOS officeHome？

### ISSUE THREAD

**Issue by Engineer-yangshuai** [sbraconnier/jodconverter#33]
/Applications/OpenOffice.app/Contents？

Exception in thread "Thread-38" java.lang.IllegalStateException: officeHome not set and could not be auto-detected
	at org.jodconverter.office.LocalOfficeUtils.validateOfficeHome(LocalOfficeUtils.java:317)
	at org.jodconverter.office.LocalOfficeManager$Builder.build(LocalOfficeManager.java:136)
	at org.jodconverter.office.LocalOfficeManager.install(LocalOfficeManager.java:67)
	at com.doc.tools.Office2PdfTool.run(Office2PdfTool.java:91)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Engineer-yangshuai** [comment]
It has been solved，thanks！

**Comment by sbraconnier** [comment]
Glad to hear that!

**Comment by daftyw** [comment]
@ys028 How you solved your issue ?
