### ISSUE TITLE
Using pipeNames causes crash with LibreOffice 6

### ISSUE THREAD

**Issue by ratcashdev** [sbraconnier/jodconverter#70]
The following test (added by me) fails (LocalOfficeManagerITest.java):
```
@Test
  public void start_using_pipeNames() throws Exception {

    final LocalOfficeManager manager = LocalOfficeManager.builder().pipeNames("test").build();
    try {
      manager.start();
    } finally {
      manager.stop();
    }
  }
```
results in a JVM crash. The soffice.bin is running.
```
Starting a Gradle Daemon, 1 busy and 1 stopped Daemons could not be reused, use --status for details
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:54686'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:134)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:272)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:260)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:254)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:132)
        ... 7 more
```
If using port numbers, it works OK.

Windows 7, JDK 1.8_162 64bit, Libreoffice 6.0.3 64 bit
Tested against latest mater, commit 7f907de10187cc44694aeb933537c118e5f3292b

**Comment by ratcashdev** [comment]
save with 1.8_172

**Comment by sbraconnier** [comment]
As the configuration [says](https://github.com/sbraconnier/jodconverter/wiki/Configuration#1234portnumbersandorcapital_abcdpipenames), you have to set the `java.library.path` VM property when using pipes.

For me on Windows, adding this property:

`"-Djava.library.path=C:\Program Files\LibreOffice\program"`

with LibreOffice 6+ to the WM arguments (run configuration on Eclipse) is enough to make your test succeeded.

**Comment by ratcashdev** [comment]
```
 @Test
  public void start_using_pipeNames() throws Exception {
    System.setProperty("java.library.path", "C:/Program Files/LibreOffice/program");
    final LocalOfficeManager manager = LocalOfficeManager.builder().pipeNames("test").build();
    try {
      manager.start();
    } finally {
      manager.stop();
    }
  }
```
is successful. Maybe we could add this test to the set.
Truth be told, I wasn't aware of the docs. Also, on the internet some ppl said, the `java.library.path` property did not help them and instead they had to put that very path on the %PATH% environment variable, which I did. While this made the jpipe.dll accessible to java, was not enough to make it work completely.
Thank you for the quick help!

**Comment by ratcashdev** [comment]
as a matter of fact, if I remove the LO path from %PATH%, then I still get the exception:
`Caused by: java.lang.UnsatisfiedLinkError: no jpipe in java.library.path`. So just setting the `java.library.path` is not enough, jpipe.dll must also be on %PATH% (or somehow accessible to java.exe)
