### ISSUE TITLE
soffice can't start (Ubuntu 16.04, LibreOffice 5.1.6.2, Java 8)

### ISSUE THREAD

**Issue by janssen** [sbraconnier/jodconverter#75]
I'm trying to use LocalConverter to convert a file, but I can't seem to start LibreOffice.  This is using the latest Github master branch.  I've updated OfficeProcess to (1) use double-hyphens for the command-line flags where soffice says it should, and (2) spit out the command-line so that I can see what it is.

```
$ java -classpath jodconverter-local-4.2.1-SNAPSHOT.jar:jodconverter-core-4.2.1-SNAPSHOT.jar:slf4j-jdk14-1.7.25.jar:slf4j-api-1.7.25.jar:commons-lang3-3.7.jar:commons-io-2.6.jar:/usr/lib/libreoffice/program/classes/commonwizards.jar:/usr/lib/libreoffice/program/classes/form.jar:/usr/lib/libreoffice/program/classes/hsqldb.jar:/usr/lib/libreoffice/program/classes/java_uno.jar:/usr/lib/libreoffice/program/classes/juh.jar:/usr/lib/libreoffice/program/classes/jurt.jar:/usr/lib/libreoffice/program/classes/query.jar:/usr/lib/libreoffice/program/classes/report.jar:/usr/lib/libreoffice/program/classes/ridl.jar:/usr/lib/libreoffice/program/classes/ScriptFramework.jar:/usr/lib/libreoffice/program/classes/ScriptProviderForJava.jar:/usr/lib/libreoffice/program/classes/sdbc_hsqldb.jar:/usr/lib/libreoffice/program/classes/smoketest.jar:/usr/lib/libreoffice/program/classes/table.jar:/usr/lib/libreoffice/program/classes/unoil.jar:/usr/lib/libreoffice/program/classes/unoloader.jar:/usr/lib/libreoffice/program/classes/XMergeBridge.jar:/usr/lib/libreoffice/program/classes/xmerge.jar:. convert /home/wjanssen/Downloads/syllabus.docx /tmp/bar.pdf
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Start' and waiting...
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcess prepareProcessBuilder
INFO: Command: /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 --invisible --norestore --nofirststartwizard --nologo --nodefault --nolockcheck --headless --nocrashreport
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcess start
INFO: Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcess start
INFO: Started process; pid = 17235
May 01, 2018 9:45:18 AM convert main
SEVERE: Can't start LibreOffice: org.jodconverter.office.OfficeException: Office process died with exit code 77
May 01, 2018 9:45:18 AM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Stopping the office manager pool...
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Stop' and waiting...
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcess forciblyTerminate
INFO: Trying to forcibly terminate process: 'host=127.0.0.1,port=2002,tcpNoDelay=1'; pid: 17235
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcessManager doTerminateProcess
INFO: process forcibly terminated with code 77
May 01, 2018 9:45:18 AM org.jodconverter.office.OfficeProcessManager doEnsureProcessExited
INFO: process exited with code 77
May 01, 2018 9:45:18 AM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Office manager stopped
```

**Comment by janssen** [comment]
I get the same error with an unmodified OfficeProcess.

**Comment by sbraconnier** [comment]
Could you please set the logging level to DEBUG and post back the console here ?

**Comment by janssen** [comment]
How do I do that?

**Comment by sbraconnier** [comment]
you are using the jodconverter-cli module ?

**Comment by janssen** [comment]
No, my own code.  "local" and "core".  Here's the code:

```java
/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.HashMap;
import java.util.logging.Logger;
import java.util.logging.Level;

import org.jodconverter.document.DefaultDocumentFormatRegistry;
import org.jodconverter.document.DocumentFormatRegistry;
import org.jodconverter.document.DocumentFormat;
import org.jodconverter.office.LocalOfficeManager;
import org.jodconverter.office.OfficeException;
import org.jodconverter.office.OfficeManager;
import org.jodconverter.office.OfficeConnectionProtocol;
import org.jodconverter.LocalConverter;
import org.jodconverter.task.LocalConversionTask;

/**
 */
public final class convert
{
    /*
     * debug flag
     */
    private boolean debug = false;

    /**
     * private constructor.
    */
    private convert()
    {
        //static class
    }

    static private OfficeManager officeManager = null;
        
    static private DocumentFormatRegistry formatRegistry = null;

    static private Logger logger = Logger.getGlobal();

    private static class ShutdownHandler extends Thread {
        public void run () {
            try {
                if (officeManager != null) {
                    logger.info("Stopping officeManager " + officeManager);
                    officeManager.stop();
                }
            } catch (Exception x) {
                x.printStackTrace(System.err);
            }
        }
    }

    /**
     * @param args Command line arguments, should be one and a reference to a file.
     *
     * @throws IOException if there is an error reading the document or extracting the text.
     */
    public static void main( String[] args ) throws IOException, OfficeException
    {
        if (args.length != 2) {
            System.err.println("Usage: convert INPUT-FILE OUTPUT-FILE");
            System.exit(1);
        }

        // suppress the Dock icon on OS X
        System.setProperty("apple.awt.UIElement", "true");

        // tell log4j to stop its yapping
        System.setProperty("log4j.defaultInitOverride", "true");

        // Get finest possible logging
        logger.setLevel(Level.FINEST);

        officeManager = LocalOfficeManager
            .builder()
            .install()
            .build();
        try {
            officeManager.start();
        } catch (OfficeException x) {
            logger.severe(String.format("Can't start LibreOffice: %s", x));
            officeManager.stop();
            officeManager = null;
            System.exit(1);
        }

        formatRegistry = DefaultDocumentFormatRegistry.getInstance();

        Runtime.getRuntime().addShutdownHook(new ShutdownHandler());

        File inputFile = new File(args[0]);
        File outputFile = new File(args[1]);

        Map<String, Object> filterData = new HashMap<>();
        filterData.put("UseTaggedPDF", true);
        Map<String, Object> storeProperties= new HashMap<>();
        storeProperties.put("FilterData", filterData);
        storeProperties.put("Overwrite", true);

        LocalConverter
            .builder()
            .storeProperties(storeProperties)
            .build()
            .convert(inputFile)
            .to(outputFile)
            .execute();
    }
}
```

**Comment by sbraconnier** [comment]
Could you please try with this snapshot of the jodconverter-cli module:

[jodconverter-cli-4.2.1-SNAPSHOT.zip](https://github.com/sbraconnier/jodconverter/files/1965201/jodconverter-cli-4.2.1-SNAPSHOT.zip)

Then if you have the same error, I will be able to tell you how to set the logging level to DEBUG.

By the way, you don't need a shudown hook the way you use jodconverter. You can have a look at the [Convert](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-cli/src/main/java/org/jodconverter/cli/Convert.java) class of the jodconverter-cli module for an example on how a converter is created for a command line tool.

**Comment by janssen** [comment]
Thanks for the tip.  I wasn't sure about that.  I'll try the snapshot and report back.

**Comment by sbraconnier** [comment]
Maybe there is some missing jars on your command line (classpath). All the dependencies of the jodconverter-cli module are in the lib directory. Maybe you could try to compare your command classpath arguments with the libraries located in the lib directory.

**Comment by sbraconnier** [comment]
The shutdown hook is supposed to be a fail safe, but it's not the clean way to ensure the office process is stopped.

You are supposed to do it this way:

```java
......
final LocalOfficeManager officeManager = LocalOfficeManager.make(); 
try {
    // Start an office process and connect to the started instance (on port 2002).
    officeManager.start();

    File inputFile = new File(args[0]);
    File outputFile = new File(args[1]);

    Map<String, Object> filterData = new HashMap<>();
    filterData.put("UseTaggedPDF", true);
    Map<String, Object> storeProperties= new HashMap<>();
    storeProperties.put("FilterData", filterData);
    storeProperties.put("Overwrite", true);

    LocalConverter
        .builder()
        .officeManager(officeManager)
        .storeProperties(storeProperties)
        .build()
        .convert(inputFile)
        .to(outputFile)
        .execute();
} finally {
    // Stop the office process
    OfficeUtils.stopQuietly(officeManager);
}
```

**Comment by janssen** [comment]
Got it.  OK, now the only problem I'm seeing is that the soffice process is started twice:

```java
+ java -Djava.util.logging.config.file=.logging.config -classpath jodconverter-local-4.2.1-SNAPSHOT.jar:jodconverter-core-4.2.1-SNAPSHOT.jar:slf4j-jdk14-1.7.25.jar:slf4j-api-1.7.25.jar:commons-lang3-3.7.jar:commons-io-2.6.jar:gson-2.8.2.jar:/usr/lib/libreoffice/program/classes/commonwizards.jar:/usr/lib/libreoffice/program/classes/form.jar:/usr/lib/libreoffice/program/classes/hsqldb.jar:/usr/lib/libreoffice/program/classes/java_uno.jar:/usr/lib/libreoffice/program/classes/juh.jar:/usr/lib/libreoffice/program/classes/jurt.jar:/usr/lib/libreoffice/program/classes/query.jar:/usr/lib/libreoffice/program/classes/report.jar:/usr/lib/libreoffice/program/classes/ridl.jar:/usr/lib/libreoffice/program/classes/ScriptFramework.jar:/usr/lib/libreoffice/program/classes/ScriptProviderForJava.jar:/usr/lib/libreoffice/program/classes/sdbc_hsqldb.jar:/usr/lib/libreoffice/program/classes/smoketest.jar:/usr/lib/libreoffice/program/classes/table.jar:/usr/lib/libreoffice/program/classes/unoil.jar:/usr/lib/libreoffice/program/classes/unoloader.jar:/usr/lib/libreoffice/program/classes/XMergeBridge.jar:/usr/lib/libreoffice/program/classes/xmerge.jar:. convert /home/wjanssen/Downloads/syllabus.docx /tmp/bar.pdf
May 02, 2018 12:03:35 PM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Start' and waiting...
May 02, 2018 12:03:35 PM org.jodconverter.office.OfficeProcess prepareProcessBuilder
INFO: Command: /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 --invisible --norestore --nofirststartwizard --nologo --nodefault --nolockcheck --headless --nocrashreport
May 02, 2018 12:03:35 PM org.jodconverter.office.OfficeProcess start
INFO: Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
May 02, 2018 12:03:35 PM org.jodconverter.office.OfficeProcess start
INFO: Started process; pid = 24432
May 02, 2018 12:03:36 PM org.jodconverter.office.ConnectRetryable attempt
WARNING: Office process died with exit code 81; restarting it
May 02, 2018 12:03:36 PM org.jodconverter.office.OfficeProcess prepareProcessBuilder
INFO: Command: /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 --invisible --norestore --nofirststartwizard --nologo --nodefault --nolockcheck --headless --nocrashreport
May 02, 2018 12:03:36 PM org.jodconverter.office.OfficeProcess start
INFO: Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
May 02, 2018 12:03:36 PM org.jodconverter.office.OfficeProcess start
INFO: Started process; pid = 24452
May 02, 2018 12:03:36 PM org.jodconverter.office.OfficeConnection connect
INFO: Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
May 02, 2018 12:03:36 PM org.jodconverter.task.LocalConversionTask execute
INFO: Executing local conversion task...
May 02, 2018 12:03:36 PM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Stopping the office manager pool...
May 02, 2018 12:03:36 PM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Stop' and waiting...
May 02, 2018 12:03:36 PM org.jodconverter.office.OfficeConnection disposing
INFO: Disconnected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
May 02, 2018 12:03:37 PM org.jodconverter.office.OfficeProcessManager doEnsureProcessExited
INFO: process exited with code 0
May 02, 2018 12:03:37 PM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Office manager stopped
```
Thanks for all this help, by the way!

**Comment by sbraconnier** [comment]
No problem!

What you see is related to this "problem":

https://code.google.com/archive/p/jodconverter/issues/84

When we start LibreOffice without a "profile" directory, it is considered as a first start. When this happens, Only the profile directory is created and LibreOffice is restarted.

This behavior can be avoided using a [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir).

You can look at #48 for a better explanation.

**Comment by janssen** [comment]
Thanks!

**Comment by janssen** [comment]
I don't suppose there's a method in jodconverter to get the path to that directory (the user's template directory) programmatically?

**Comment by janssen** [comment]
Broken again.  Same code!  Error appears to be a negative PID reported.

```
$ java -Djava.util.logging.config.file=.logging.config -classpath jodconverter-local-4.2.1-SNAPSHOT.jar:jodconverter-core-4.2.1-SNAPSHOT.jar:slf4j-jdk14-1.7.25.jar:slf4j-api-1.7.25.jar:commons-lang3-3.7.jar:commons-io-2.6.jar:gson-2.8.2.jar:pdfbox-app-2.0.9.jar:/usr/lib/libreoffice/program/classes/commonwizards.jar:/usr/lib/libreoffice/program/classes/form.jar:/usr/lib/libreoffice/program/classes/hsqldb.jar:/usr/lib/libreoffice/program/classes/java_uno.jar:/usr/lib/libreoffice/program/classes/juh.jar:/usr/lib/libreoffice/program/classes/jurt.jar:/usr/lib/libreoffice/program/classes/query.jar:/usr/lib/libreoffice/program/classes/report.jar:/usr/lib/libreoffice/program/classes/ridl.jar:/usr/lib/libreoffice/program/classes/ScriptFramework.jar:/usr/lib/libreoffice/program/classes/ScriptProviderForJava.jar:/usr/lib/libreoffice/program/classes/sdbc_hsqldb.jar:/usr/lib/libreoffice/program/classes/smoketest.jar:/usr/lib/libreoffice/program/classes/table.jar:/usr/lib/libreoffice/program/classes/unoil.jar:/usr/lib/libreoffice/program/classes/unoloader.jar:/usr/lib/libreoffice/program/classes/XMergeBridge.jar:/usr/lib/libreoffice/program/classes/xmerge.jar:. convert /home/wjanssen/Downloads/syllabus.docx /tmp/b2.pdf
Starting...
May 09, 2018 9:21:10 AM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Start' and waiting...
May 09, 2018 9:21:10 AM org.jodconverter.office.OfficeProcess prepareProcessBuilder
INFO: Command: /usr/lib/libreoffice/program/soffice.bin --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 --invisible --norestore --nofirststartwizard --nologo --nodefault --nolockcheck --headless --nocrashreport
May 09, 2018 9:21:10 AM org.jodconverter.office.OfficeProcess start
INFO: Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
May 09, 2018 9:21:10 AM org.jodconverter.office.OfficeProcess start
INFO: Started process; pid = -2
May 09, 2018 9:21:10 AM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Stopping the office manager pool...
May 09, 2018 9:21:10 AM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Stop' and waiting...
May 09, 2018 9:21:10 AM org.jodconverter.office.OfficeProcess forciblyTerminate
INFO: Trying to forcibly terminate process: 'host=127.0.0.1,port=2002,tcpNoDelay=1'; pid: -2
May 09, 2018 9:21:11 AM org.jodconverter.office.OfficeProcessManager doTerminateProcess
INFO: process forcibly terminated with code 81
May 09, 2018 9:21:11 AM org.jodconverter.office.OfficeProcessManager doEnsureProcessExited
INFO: process exited with code 81
May 09, 2018 9:21:11 AM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Office manager stopped
Exception in thread "main" org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' started but its pid could not be found
	at org.jodconverter.office.OfficeProcess.start(OfficeProcess.java:360)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:100)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
$
```
Code is
```java
/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.HashMap;
import java.util.logging.Logger;
import java.util.logging.Level;

import org.jodconverter.document.DefaultDocumentFormatRegistry;
import org.jodconverter.document.DocumentFormatRegistry;
import org.jodconverter.document.DocumentFormat;
import org.jodconverter.office.LocalOfficeManager;
import org.jodconverter.office.OfficeException;
import org.jodconverter.office.OfficeManager;
import org.jodconverter.office.OfficeConnectionProtocol;
import org.jodconverter.office.OfficeUtils;
import org.jodconverter.LocalConverter;
import org.jodconverter.task.LocalConversionTask;

/**
 */
public final class convert
{
    private convert()
    {
        //static class
    }

    static private DocumentFormatRegistry formatRegistry = null;

    static private Logger logger = Logger.getGlobal();

    public static void main( String[] args ) throws IOException, OfficeException
    {
        if (args.length != 2) {
            System.err.println("Usage: convert INPUT-FILE OUTPUT-FILE");
            System.exit(1);
        }

        // suppress the Dock icon on OS X
        System.setProperty("apple.awt.UIElement", "true");

        // tell log4j to stop its yapping
        System.setProperty("log4j.defaultInitOverride", "true");

        final LocalOfficeManager officeManager = LocalOfficeManager.make(); 

        try {
            // Start an office process and connect to the started instance (on port 2002).
            System.err.println("Starting...");
            officeManager.start();
            System.err.println("Sleeping...");
            try {
                Thread.sleep(5 * 1000);
            } catch (InterruptedException x) {
            }
            System.err.println("Awake again");
            
            File inputFile = new File(args[0]);
            File outputFile = new File(args[1]);

            Map<String, Object> filterData = new HashMap<>();
            filterData.put("UseTaggedPDF", true);
            Map<String, Object> storeProperties= new HashMap<>();
            storeProperties.put("FilterData", filterData);
            storeProperties.put("Overwrite", true);

            LocalConverter
                .builder()
                .officeManager(officeManager)
                .storeProperties(storeProperties)
                .build()
                .convert(inputFile)
                .to(outputFile)
                .execute();
        } finally {
            // Stop the office process
            OfficeUtils.stopQuietly(officeManager);
        }
    }
}
```

**Comment by sbraconnier** [comment]
your classpath is quite odd... you don't need all these dependencies (frankly I'm not sure what to expect of your command line...). Try with these dependencies that you can find in the `jodconverter-cli-4.2.1-SNAPSHOT.zip`.

- commons-codec-1.11.jar
- commons-io-2.6.jar
- commons-lang3-3.7.jar
- commons-logging-1.2.jar
- gson-2.8.2.jar
- jodconverter-core-4.2.1-SNAPSHOT.jar
- jodconverter-local-4.2.1-SNAPSHOT.jar
- juh-4.1.2.jar
- jurt-4.1.2.jar
- log4j-1.2.17.jar
- ridl-4.1.2.jar
- slf4j-api-1.7.25.jar
- slf4j-log4j12-1.7.25.jar
- unoil-4.1.2.jar

**Comment by janssen** [comment]
OK, I'll give that a try.  I was putting everything from the LibreOffice program/classes directory on my classpath, as I didn't know which jars were necessary.  I'll replace that with your list and try again.

**Comment by janssen** [comment]
Tried it with your suggested classpath, and things just hang:

```
+ java -Djava.util.logging.config.file=.logging.config -classpath .:commons-codec-1.11.jar:commons-io-2.6.jar:commons-lang3-3.7.jar:commons-logging-1.2.jar:gson-2.8.2.jar:jodconverter-core-4.2.1-SNAPSHOT.jar:jodconverter-local-4.2.1-SNAPSHOT.jar:juh-4.1.2.jar:jurt-4.1.2.jar:log4j-1.2.17.jar:ridl-4.1.2.jar:slf4j-api-1.7.25.jar:slf4j-log4j12-1.7.25.jar:unoil-4.1.2.jar convert /home/wjanssen/Downloads/syllabus.docx /tmp/b2.pdf
os is Linux
templatePath is /home/wjanssen/.config/libreoffice/4/user
Starting...
log4j:WARN No appenders could be found for logger (org.jodconverter.office.OfficeProcessManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
I'm *really* not interested in learning the minutiae of log4j...

**Comment by sbraconnier** [comment]
Your template path should be /home/wjanssen/.config/libreoffice/4

These are just log4j warnings because you didn't provide a log4j configuration file. They can be ignored (but you won't have any logs).

There is probably something wrong with your classpath again. Hard for me to say, since I don't know the directory structure you are using.

Take a look at the `bin` directory of the `jodconverter-cli-4.2.1-SNAPSHOT`. There is a jodconverter-cli file where you can find an example of the classpath argument.

**Comment by janssen** [comment]
I'm using almost the exact classpath you told me to use (I did switch out log4j for straight Java logging), extracted from the SNAPSHOT zip file.  All the jars are in my current working directory.

```
$ java -classpath .:commons-codec-1.11.jar:commons-io-2.6.jar:commons-lang3-3.7.jar:commons-logging-1.2.jar:gson-2.8.2.jar:jodconverter-core-4.2.1-SNAPSHOT.jar:jodconverter-local-4.2.1-SNAPSHOT.jar:juh-4.1.2.jar:jurt-4.1.2.jar:log4j-1.2.17.jar:ridl-4.1.2.jar:slf4j-api-1.7.25.jar:slf4j-jdk14-1.7.25.jar:unoil-4.1.2.jar convert /home/wjanssen/Downloads/syllabus.docx /tmp/b2.pdf
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Start' and waiting...
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcess start
INFO: Starting process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcess start
INFO: Started process; pid = -2
May 09, 2018 12:07:18 PM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Stopping the office manager pool...
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcessManager submitAndWait
INFO: Submitting task 'Stop' and waiting...
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcess forciblyTerminate
INFO: Trying to forcibly terminate process: 'host=127.0.0.1,port=2002,tcpNoDelay=1'; pid: -2
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcessManager doTerminateProcess
INFO: process forcibly terminated with code 81
May 09, 2018 12:07:18 PM org.jodconverter.office.OfficeProcessManager doEnsureProcessExited
INFO: process exited with code 81
May 09, 2018 12:07:18 PM org.jodconverter.office.AbstractOfficeManagerPool doStop
INFO: Office manager stopped
Exception in thread "main" org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' started but its pid could not be found
	at org.jodconverter.office.OfficeProcess.start(OfficeProcess.java:354)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:100)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The bad PID seems to be the issue.

**Comment by janssen** [comment]
Here's the program, again.  This is LibreOffice 5.1.6.2, on Ubuntu 16.04.

```java
/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.HashMap;
import java.util.logging.Logger;
import java.util.logging.Level;

import org.jodconverter.document.DefaultDocumentFormatRegistry;
import org.jodconverter.document.DocumentFormatRegistry;
import org.jodconverter.document.DocumentFormat;
import org.jodconverter.office.LocalOfficeManager;
import org.jodconverter.office.OfficeException;
import org.jodconverter.office.OfficeManager;
import org.jodconverter.office.OfficeConnectionProtocol;
import org.jodconverter.office.OfficeUtils;
import org.jodconverter.LocalConverter;
import org.jodconverter.task.LocalConversionTask;

/**
 */
public final class convert
{
    private convert()
    {
        //static class
    }

    static private DocumentFormatRegistry formatRegistry = null;

    static private Logger logger = Logger.getGlobal();

    public static void main( String[] args ) throws IOException, OfficeException
    {
        if (args.length != 2) {
            System.err.println("Usage: convert INPUT-FILE OUTPUT-FILE");
            System.exit(1);
        }

        // suppress the Dock icon on OS X
        System.setProperty("apple.awt.UIElement", "true");

        // tell log4j to stop its yapping
        System.setProperty("log4j.defaultInitOverride", "true");

        // tell the office manager builder about the profile dir, and build the office manager
        final LocalOfficeManager officeManager = LocalOfficeManager.make();

        try {
            // Start an office process and connect to the started instance
            officeManager.start();
            
            File inputFile = new File(args[0]);
            File outputFile = new File(args[1]);

            Map<String, Object> filterData = new HashMap<>();
            filterData.put("UseTaggedPDF", true);
            Map<String, Object> storeProperties= new HashMap<>();
            storeProperties.put("FilterData", filterData);
            storeProperties.put("Overwrite", true);

            LocalConverter
                .builder()
                .officeManager(officeManager)
                .storeProperties(storeProperties)
                .build()
                .convert(inputFile)
                .to(outputFile)
                .execute();
        } finally {
            // Stop the office process
            OfficeUtils.stopQuietly(officeManager);
        }
    }
}
```

**Comment by janssen** [comment]
I rebooted my machine, and it works again!!  What in the world?

**Comment by sbraconnier** [comment]
This is effectively odd...

**Comment by sbraconnier** [comment]
I'll close this one for now, feel free to reopen it if you hit the problem again. Since now you use the jdk logging adapter, you will be able to adjust the logging level in order to see the DEBUG messages from jodconverter.
