### ISSUE TITLE
Is LocalOfficeManager ignoring its builder?

### ISSUE THREAD

**Issue by fdellwing** [sbraconnier/jodconverter#80]
So we have the following code:

```java
@ManagedBean(eager = true)
@ApplicationScoped
public class OfficeWorker {

    public OfficeWorker() throws OfficeException {

        LocalOfficeManager officeManager;

        try {
            officeManager = LocalOfficeManager.builder()
                    .portNumbers(2002, 2003, 2004)
                    .officeHome("/opt/libreoffice6.0")
                    .build()
                    .install();

            officeManager.start();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
```

```
Schwerwiegend:   java.lang.IllegalStateException: officeHome not set and could not be auto-detected
	at org.jodconverter.office.LocalOfficeUtils.validateOfficeHome(LocalOfficeUtils.java:311)
	at org.jodconverter.office.LocalOfficeManager$Builder.build(LocalOfficeManager.java:136)
	at org.jodconverter.office.LocalOfficeManager.install(LocalOfficeManager.java:67)
	at export.OfficeWorker.<init>(OfficeWorker.java:31)
```

So we told him to use `/opt/libreoffice6.0` as officeHome and open the ports `2002, 2003 and 2004`.

What he will do is: Trying to auto-detect officeHome under `/usr/lib/libreoffice`.

If you run `ln -s /opt/libreoffice6.0 /usr/lib/libreoffice` he will run `/usr/lib/libreoffice/program/soffice.bin` with only port 2002 opened.

Please explain why this happens and how to fix it.

**Comment by sbraconnier** [comment]
Hi there,

It should be:

            officeManager = LocalOfficeManager.builder()
                    .portNumbers(2002, 2003, 2004)
                    .officeHome("/opt/libreoffice6.0")
                    // install() must come before build()
                    .install()
                    .build();

instead of:

            officeManager = LocalOfficeManager.builder()
                    .portNumbers(2002, 2003, 2004)
                    .officeHome("/opt/libreoffice6.0")
                    .build()
                    .install();

The way you are creating your manager is the same as if you would have done:

            officeManager = LocalOfficeManager.install();

You are accessing the static method `install` of the `LocalOfficeManager` class, not the non-static `install` method of the `LocalOfficeManager.Builder` instance. Thus, you are creating another manager using the default configuration and the one you created using the custom ports and office home is never used!
