### ISSUE TITLE
Error to convert files

### ISSUE THREAD

**Issue by cunhazera** [sbraconnier/jodconverter#83]
When I try to run this code I get an exception:
``` java
 final LocalOfficeManager newManager = LocalOfficeManager.install();
                try {
                    newManager.start();
                    JodConverter
                            .convert(source)
                            .to(tempFile)
                            .execute();
                } catch (Throwable e) {
                    log.error("Error converting the document ", e);
                } finally {
                    OfficeUtils.stopQuietly(newManager);
                }
```

Exception:
```
Error converting the document : java.lang.ExceptionInInitializerError
at org.jodconverter.document.DefaultDocumentFormatRegistry.getInstance(DefaultDocumentFormatRegistry.java:382)
at org.jodconverter.document.DefaultDocumentFormatRegistry.<clinit>(DefaultDocumentFormatRegistry.java:54)
at org.jodconverter.job.AbstractConverter.<init>(AbstractConverter.java:64)
at org.jodconverter.LocalConverter.<init>(LocalConverter.java:93)
at org.jodconverter.LocalConverter.<init>(LocalConverter.java:49)
at org.jodconverter.LocalConverter$Builder.build(LocalConverter.java:202)
at org.jodconverter.LocalConverter.make(LocalConverter.java:73)
at org.jodconverter.JodConverter.convert(JodConverter.java:48)
...
Caused by: java.lang.RuntimeException: Unable to invoke no-args constructor for class org.jodconverter.document.DocumentFormat. Registering an InstanceCreator with Gson for this type may fix this problem.
 	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
 	at com.google.gson.Gson.fromJson(Gson.java:888)
 	at com.google.gson.Gson.fromJson(Gson.java:853)
 	at com.google.gson.Gson.fromJson(Gson.java:802)
 	at org.jodconverter.document.JsonDocumentFormatRegistry.readJsonArray(JsonDocumentFormatRegistry.java:75)
 	at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:59)
 	at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:47)
 	at org.jodconverter.document.DefaultDocumentFormatRegistry$InstanceHolder.create(DefaultDocumentFormatRegistry.java:368)
 	at org.jodconverter.document.DefaultDocumentFormatRegistry$InstanceHolder.<clinit>(DefaultDocumentFormatRegistry.java:362)
 	... 318 more
 Caused by: java.lang.UnsupportedOperationException: Cannot allocate class org.jodconverter.document.DocumentFormat
 	at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)
 	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
 	... 330 more
```

**Comment by javydreamercsw** [comment]
Probably need to specify which version you are using. Might be a version mismatch.

**Comment by sbraconnier** [comment]
Sorry for the late answer, I'm on vacation right now :). Thanks @javydreamercsw for the comment, which is what I would have asked for. Which version are you using ? This exception is strange. It is like if your jodconverter-local version and jodconverter-core version were not the same...

**Comment by cunhazera** [comment]
I already found a way out. Thank u guys.
